import { GOVERNANCE_RULES } from './shared-rules.js';
import {
  SHARED_REVIEW_LOOP,
  DISCOVERY_REVIEW_CAPTURE,
  DISCOVERY_REVIEW_DONE_WHEN,
} from './shared-review-loop.js';

export const ARCHITECTURE_COMMAND = `
---
description: Create or revise an Architecture Decision Record (ADR) with mandatory independent subagent review.
agent: build
---

You are managing a FlowGuard-controlled development workflow.

## Goal

Create or revise an Architecture Decision Record (ADR) for the current FlowGuard session, then obtain mandatory independent review (parity with /plan and /implement).

## Steps

### Phase 1: Check State

1. Call \`flowguard_status\` to verify a session exists in READY or ARCHITECTURE phase.
   - If no session: call \`flowguard_hydrate\` first.
   - If phase does not allow /architecture: report the current phase and stop.
${DISCOVERY_REVIEW_CAPTURE}

### Phase 2: Submit ADR

2. If in READY phase (new ADR):
   - Gather the architecture decision context from the user's request and any relevant ticket text.
   - Generate an ADR in MADR format with the mandatory sections \`## Context\`, \`## Decision\`, and \`## Consequences\`.
   - Call \`flowguard_architecture({ title, adrText })\` with only \`title\` and the full ADR markdown set. The ADR id is auto-generated by the tool.
3. If in ARCHITECTURE phase (revision after changes_requested):
   - Read the latest review findings from session state.
   - Revise the ADR to address the feedback.
   - Submit the revised verdict in step 4 below — do NOT call \`flowguard_architecture({ title, adrText })\` again, that path is for a brand-new ADR.
4. Read the response. The \`next\` field contains the review workflow instructions.

### Phase 3: Review Loop

5. Follow the \`next\` field instructions exactly:
${SHARED_REVIEW_LOOP({
  toolName: 'flowguard_architecture',
  artifactName: 'ADR',
  reviseParams: 'adrText: <revised>',
  changesRequestedExtra: '',
  strictRecoveryCall: 'flowguard_architecture({ title: <same title>, adrText: <same ADR text> })',
  strictRecoveryVerb: 'Re-submit',
  strictRecoveryNoun: 're-submissions',
  iterationNote: '(max iterations from policy.maxSelfReviewIterations)',
  repeatStep: 5,
  subagentExtra:
    ' with subagent_type "flowguard-reviewer", supplying the ADR text, ADR title, ticket text, iteration, and planVersion as instructed',
  fallbackExtra: '',
  unableDescription:
    'e.g., contradictory context, missing prerequisites, or scope ambiguity that prevents critique',
  unableRecoveryA: 'resolve the prerequisite ambiguity',
  unableRecoveryB:
    'submit a substantially-revised ADR (a fresh flowguard_architecture({ title, adrText }) submission, which starts a new review obligation)',
})}

6. Report the ADR title, ID, current phase, and whether human review is needed.

## Rules

- The ADR includes \`## Context\`, \`## Decision\`, and \`## Consequences\` sections.
- Always complete the independent review before proceeding (use plugin findings or the reviewer subagent).
- When revising an ADR, include the COMPLETE ADR text (not a diff).
- Do not substitute self-review for independent review when subagent review is active.
- Do not call implementation tools (write/edit/bash) during /architecture.
- Do not auto-chain into /plan or /implement after ADR approval — stop and let the user decide.

## Example (correct tool sequences)

Happy path:
1. \`flowguard_status\` → phase: READY
2. \`flowguard_architecture({ title, adrText })\` → returns \`next: "INDEPENDENT_REVIEW_REQUIRED: ..."\` or "INDEPENDENT_REVIEW_COMPLETED: ..."
3. (If REQUIRED) Call flowguard-reviewer subagent via Task tool, parse ReviewFindings.
4. \`flowguard_architecture({ reviewVerdict: "approve" })\` → ARCH_REVIEW

Revision path (when review returns changes_requested):
1. \`flowguard_architecture({ reviewVerdict: "changes_requested", adrText: <revised> })\`
2. → new review starts, returns \`next: "INDEPENDENT_REVIEW_REQUIRED: ..."\` for the next iteration
3. After re-reviewing, \`flowguard_architecture({ reviewVerdict: "approve" })\` → ARCH_REVIEW

${GOVERNANCE_RULES}
## Presentation

- If the response contains a \`reviewCard\` field, display its markdown verbatim — never summarize, truncate, or omit it.
- The reviewCard contains the formatted architecture review with ADR details, findings, and next actions.
- This is mandatory output: the user relies on it to make their review decision.

## Done-when

- ADR is created or revised with Context, Decision, and Consequences sections.
- Independent review loop has converged (approved or max iterations reached).
${DISCOVERY_REVIEW_DONE_WHEN}
- If \`reviewCard\` is present in the tool response, it is displayed verbatim in the output.
- Phase has reached ARCH_REVIEW (ready for human review).
- Response ends with a \`Next action:\` line.
`;
