import { GOVERNANCE_RULES } from './shared-rules.js';
import {
  SHARED_REVIEW_LOOP,
  DISCOVERY_REVIEW_CAPTURE,
  DISCOVERY_REVIEW_DONE_WHEN,
} from './shared-review-loop.js';

export const ARCHITECTURE_COMMAND = `
---
description: Create or revise an Architecture Decision Record (ADR) with mandatory independent subagent review.
agent: build
---

You are managing a FlowGuard-controlled development workflow.

## Goal

Create or revise an Architecture Decision Record (ADR) for the current FlowGuard session, then obtain mandatory independent review (parity with /plan and /implement).

## Steps

### Phase 1: Check State

1. Call \`flowguard_status\` to verify a session exists in READY or ARCHITECTURE phase.
   - If no session: call \`flowguard_hydrate\` first.
   - If phase does not allow /architecture: report the current phase and stop.
${DISCOVERY_REVIEW_CAPTURE}

### Phase 2: Submit ADR

2. If in READY phase (new ADR):
   - Gather the architecture decision context from the user's request and any relevant ticket text.
   - Generate an ADR in MADR format with the mandatory sections \`## Context\`, \`## Decision\`, and \`## Consequences\`.
   - Derive structured claim declarations for the decision. Each claim names ONE
     falsifiable architectural assertion, its governing ADR section, and the review
     evidence required to assess it:
     - \`claimId\`: fresh UUID.
     - \`statement\`: the architectural assertion or forbidden state.
     - \`critical\`: true when the decision is unsafe to approve without this claim.
     - \`authoritySectionId\`: the governing ADR section (e.g. \`decision\`).
     - \`requiredReviewEvidence\`: named review coverage the reviewer must provide.
     - \`assumptions\` (optional): unproven dependencies the claim rests on.
   - Call \`flowguard_architecture({ title, adrText, claims })\` with the title, the full
     ADR markdown, and those declarations. The ADR id is auto-generated by the tool.
3. If in ARCHITECTURE phase (revision after changes_requested):
   - Read the latest review findings from session state.
   - Revise the ADR to address the feedback.
   - Submit the revised verdict in step 4 below — do NOT call \`flowguard_architecture({ title, adrText, claims })\` again, that path is for a brand-new ADR.
4. Read the response. The \`next\` field contains the review workflow instructions.

### Phase 3: Review Loop

5. Follow the \`next\` field instructions exactly:
${SHARED_REVIEW_LOOP({
  toolName: 'flowguard_architecture',
  artifactName: 'ADR',
  reviseParams: 'adrText: <revised>, claims: <revised>',
  changesRequestedExtra: '',
  strictRecoveryCall:
    'flowguard_architecture({ title: <same title>, adrText: <same ADR text>, claims: <same claims> })',
  strictRecoveryVerb: 'Re-submit',
  strictRecoveryNoun: 're-submissions',
  iterationNote: '(max iterations from policy.maxSelfReviewIterations)',
  repeatStep: 5,
  subagentExtra:
    ' with subagent_type "flowguard-reviewer", supplying the ADR text, ADR title, ticket text, iteration, and planVersion as instructed',
  fallbackExtra: '',
  unableDescription:
    'e.g., contradictory context, missing prerequisites, or scope ambiguity that prevents critique',
  unableRecoveryA: 'resolve the prerequisite ambiguity',
  unableRecoveryB:
    'submit a substantially-revised ADR (a fresh flowguard_architecture({ title, adrText, claims }) submission, which starts a new review obligation)',
})}

6. Report the ADR title, ID, current phase, and whether human review is needed.

## Rules

- The ADR includes \`## Context\`, \`## Decision\`, and \`## Consequences\` sections.
- Declare structured \`claims\` on every new ADR submission; they are bound into the
  architecture approval certificate and surfaced to the reviewer.
- Architecture claims are advisory by design: they are recorded as \`derived_signal\`
  and never block an approval, because no executable provider covers ADR review
  evidence. Do not present them as proven.
- Always complete the independent review before proceeding (use plugin findings or the reviewer subagent).
- When revising an ADR, include the COMPLETE ADR text (not a diff).
- Do not substitute self-review for independent review when subagent review is active.
- Do not call implementation tools (write/edit/bash) during /architecture.
- Do not auto-chain into /plan or /implement after ADR approval — stop and let the user decide.

## Example (correct tool sequences)

Happy path:
1. \`flowguard_status\` → phase: READY
2. \`flowguard_architecture({ title, adrText, claims })\` → returns \`next: "INDEPENDENT_REVIEW_REQUIRED: ..."\` or "INDEPENDENT_REVIEW_COMPLETED: ..."
3. (If REQUIRED) Call flowguard-reviewer subagent via Task tool. In host-task mode submit the verdict only (do NOT submit \`reviewFindings\`, not even an empty placeholder object); in SDK mode parse and pass the exact ReviewFindings.
4. \`flowguard_architecture({ reviewVerdict: "accept" })\` → ARCH_REVIEW (user gate — the USER approves via /review-decision; this call does NOT approve the ADR)

Revision path (when review returns changes_requested):
1. \`flowguard_architecture({ reviewVerdict: "changes_requested", adrText: <revised>, claims: <revised> })\`
2. → new review starts, returns \`next: "INDEPENDENT_REVIEW_REQUIRED: ..."\` for the next iteration
3. After re-reviewing, \`flowguard_architecture({ reviewVerdict: "accept" })\` → ARCH_REVIEW (user gate — the USER decides via /review-decision)

${GOVERNANCE_RULES}
## Presentation

- If \`presentation.markdown\` is present, display its markdown verbatim — never summarize, truncate, or omit it; do not append a second conclusion.
- Only when \`presentation.markdown\` is absent, display the legacy \`reviewCard\` field verbatim.
- This is mandatory output: the user relies on it to make their review decision.

## Done-when

- ADR is created or revised with Context, Decision, and Consequences sections.
- Independent review loop has reviewer evidence (reviewer accepted or iteration limit reached). Both outcomes require an explicit human decision at ARCH_REVIEW; auto-approval policies never accept an ADR.
${DISCOVERY_REVIEW_DONE_WHEN}
- If \`presentation.markdown\` is present, it is displayed verbatim; otherwise the legacy \`reviewCard\` is displayed verbatim.
- Phase has reached ARCH_REVIEW (ready for human review).
- When the canonical presentation is present it already ends with its rendered next-action
  conclusion (a \`## Decision required\` block, or a terminal message) — do NOT
  append a separate \`Next action:\` line; the rendered conclusion is canonical.
  Only when no \`reviewCard\` is present (blocked path) does the response end with
  a \`Next action:\` line surfacing the FlowGuard blocker.
`;
