import { GOVERNANCE_RULES } from './shared-rules.js';

export const ARCHITECTURE_COMMAND = `
---
description: Create or revise an Architecture Decision Record (ADR) with mandatory independent subagent review.
---

You are managing a FlowGuard-controlled development workflow.

## Goal

Create or revise an Architecture Decision Record (ADR) for the current FlowGuard session, then obtain mandatory independent review (parity with /plan and /implement).

## Steps

### Phase 1: Check State

1. Call \`flowguard_status\` to verify a session exists in READY or ARCHITECTURE phase.
   - If no session: call \`flowguard_hydrate\` first.
   - If phase does not allow /architecture: report the current phase and stop.

### Phase 2: Submit ADR

2. If in READY phase (new ADR):
   - Gather the architecture decision context from the user's request and any relevant ticket text.
   - Generate an ADR in MADR format with the mandatory sections \`## Context\`, \`## Decision\`, and \`## Consequences\`.
   - Call \`flowguard_architecture({ title, adrText })\` with only \`title\` and the full ADR markdown set. The ADR id is auto-generated by the tool.
3. If in ARCHITECTURE phase (revision after changes_requested):
   - Read the latest review findings from session state.
   - Revise the ADR to address the feedback.
   - Submit the revised verdict in step 4 below — do NOT call \`flowguard_architecture({ title, adrText })\` again, that path is for a brand-new ADR.
4. Read the response. The \`next\` field contains the review workflow instructions.

### Phase 3: Review Loop

5. Follow the \`next\` field instructions exactly:
   - When \`next\` starts with "INDEPENDENT_REVIEW_COMPLETED": Read \`overallVerdict\` from \`pluginReviewFindings\` in the response. Pass the entire \`pluginReviewFindings\` object as \`reviewFindings\`:
     - "approve": Call \`flowguard_architecture({ selfReviewVerdict: "approve", reviewFindings: <pluginReviewFindings> })\`.
     - "changes_requested": Revise the ADR to address blocking issues, then call \`flowguard_architecture({ selfReviewVerdict: "changes_requested", adrText: <revised>, reviewFindings: <pluginReviewFindings> })\`.
     - "unable_to_review": The reviewer declared the ADR unreviewable (e.g., contradictory context, missing prerequisites, or scope ambiguity that prevents critique). The architecture tool will be BLOCKED with reason \`SUBAGENT_UNABLE_TO_REVIEW\`. DO NOT retry the review with the same ADR — that obligation is consumed. Report the reviewer's findings to the user, then either resolve the prerequisite ambiguity OR submit a substantially-revised ADR (a fresh \`flowguard_architecture({ title, adrText })\` submission, which starts a new review obligation).
   - When \`next\` starts with "INDEPENDENT_REVIEW_REQUIRED": Call the flowguard-reviewer subagent via Task tool with subagent_type "flowguard-reviewer", supplying the ADR text, ADR title, ticket text, iteration, and planVersion as instructed. Parse the JSON ReviewFindings from the subagent response, then submit the verdict with reviewFindings.
   - If review converged: Report the result.
   - If another iteration is needed: Repeat from step 5 (max iterations from policy.maxSelfReviewIterations).
   - If the tool returns BLOCKED with code \`SUBAGENT_UNABLE_TO_REVIEW\`: Stop the review loop. Treat the obligation as consumed (no retry). Surface the recovery steps from the reason payload.

6. Report the ADR title, ID, current phase, and whether human review is needed.

## Rules

- The ADR includes \`## Context\`, \`## Decision\`, and \`## Consequences\` sections.
- Always complete the independent review before proceeding (use plugin findings or the reviewer subagent).
- When revising an ADR, include the COMPLETE ADR text (not a diff).
- Do not substitute self-review for independent review when subagent review is active.
- Do not call implementation tools (write/edit/bash) during /architecture.
- Do not auto-chain into /plan or /implement after ADR approval — stop and let the user decide.

## Example (correct tool sequences)

Happy path:
1. \`flowguard_status\` → phase: READY
2. \`flowguard_architecture({ title, adrText })\` → returns \`next: "INDEPENDENT_REVIEW_REQUIRED: ..."\` or "INDEPENDENT_REVIEW_COMPLETED: ..."
3. (If REQUIRED) Call flowguard-reviewer subagent via Task tool, parse ReviewFindings.
4. \`flowguard_architecture({ selfReviewVerdict: "approve", reviewFindings: <findings> })\` → ARCH_REVIEW

Revision path (when review returns changes_requested):
1. \`flowguard_architecture({ selfReviewVerdict: "changes_requested", adrText: <revised>, reviewFindings: <findings> })\`
2. → new review starts, returns \`next: "INDEPENDENT_REVIEW_REQUIRED: ..."\` for the next iteration
3. After re-reviewing, \`flowguard_architecture({ selfReviewVerdict: "approve", reviewFindings: <new findings> })\` → ARCH_REVIEW

${GOVERNANCE_RULES}
## Presentation

- If the response contains a \`reviewCard\` field, display its markdown verbatim.
- It contains the formatted architecture review with ADR details, findings, and next actions.

## Done-when

- ADR is created or revised with Context, Decision, and Consequences sections.
- Independent review loop has converged (approved or max iterations reached).
- Phase has reached ARCH_REVIEW (ready for human review).
- Response ends with a \`Next action:\` line.
`;
