import { defineConfig } from 'vitest/config';

/**
 * Stryker-specific vitest config.
 * Governance-core files with proven individual mutation scores.
 * FlowGuard decision chain: state, audit, config, identity, machine, rails, tools,
 * review orchestrator detection/output, multi-mode validation, and canonical JSON.
 */
export default defineConfig({
  test: {
    setupFiles: ['./vitest.setup.ts'],
    include: [
      'src/adapters/**/*.test.ts',
      'src/archive/**/*.test.ts',
      'src/audit/**/*.test.ts',
      'src/config/**/*.test.ts',
      'src/identity/**/*.test.ts',
      'src/machine/**/*.test.ts',
      'src/rails/**/*.test.ts',
      'src/integration/command-aliases.test.ts',
      'src/integration/status.test.ts',
      'src/integration/tool-classification.test.ts',
      'src/integration/tools/review-validation-mode.test.ts',
      'src/integration/tools/review-validation-findings.test.ts',
      'src/integration/tools/review-validation-host-task.test.ts',
      'src/integration/tools/review-validation-host-resolution.test.ts',
      'src/integration/tools/review-validation-anti-forgery.test.ts',
      'src/integration/tools/implement-review-validation-gate.test.ts',
      'src/integration/tools/evidence-first-resolution-plan.test.ts',
      'src/integration/discovery-risk-paths.test.ts',
      'src/integration/proofgraph/claim-contract.test.ts',
      'src/integration/proofgraph/materialize-contract.test.ts',
      'src/integration/tools/pre-implementation-challenge.test.ts',
      'src/integration/tools/architecture-tool.test.ts',
      'src/integration/tools/architecture-tool-evidence-resolve.test.ts',
      'src/discovery/**/*.test.ts',
      'src/verification/**/*.test.ts',
      'src/integration/review/orchestrator.test.ts',
      'src/integration/review/orchestrator-detection.test.ts',
      'src/integration/review/orchestrator-output.test.ts',
      'src/integration/review/agent-resolution.test.ts',
      'src/integration/review/orchestrator-invoke-agent-edges.test.ts',
      'src/integration/review/structured-output-tool-part.test.ts',
      'src/integration/review/orchestrator-invoke-diagnostics.test.ts',
      'src/integration/review/orchestrator-invoke-errors.test.ts',
      'src/integration/review/orchestrator-retry-core.test.ts',
      'src/integration/review/orchestrator-retry-format-free.test.ts',
      'src/integration/review/enforcement/enforcement.test.ts',
      'src/integration/review/enforcement/findings-consistency.test.ts',
      'src/integration/review/enforcement/challenge-consistency.test.ts',
      'src/integration/review/enforcement/mutation.test.ts',
      'src/integration/review/enforcement/extraction.test.ts',
      'src/integration/review/enforcement/session.test.ts',
      'src/integration/review/verification-evidence-prompt.test.ts',
      'src/integration/review/anchor-contract-lines.test.ts',
      'src/integration/review/impl-review-prompt.test.ts',
      'src/integration/review/verification-evidence-projection.test.ts',

      'src/shared/canonical-json.test.ts',
      'src/architecture/__tests__/audit-canonicalization-ssot.test.ts',
      'src/architecture/__tests__/mode-validation-ssot.test.ts',
      'src/logging/otlp-sink.test.ts',
      'src/logging/redact.test.ts',
      'src/logging/error-serialize.test.ts',
      'src/logging/coverage-proof.test.ts',

      'src/hooks/**/*.test.ts',
      'src/mcp-server/**/*.test.ts',
      'src/templates/**/*.test.ts',
      'src/integration/plugin-audit-lifecycle-reason.test.ts',
      'src/integration/plugin-audit.test.ts',
      'src/integration/plugin-afterhooks.test.ts',
      'src/integration/plugin-afterhooks-host-task.test.ts',
      'src/integration/plugin-afterhooks-more.test.ts',
      'src/integration/plugin-beforehooks.test.ts',
      'src/integration/plugin-bootstrap.test.ts',
      'src/integration/plugin-integration.test.ts',
      'src/integration/plugin.test.ts',
      'src/integration/plugin-task-evidence.test.ts',
      'src/integration/attempt-lifecycle-e2e.test.ts',
      'src/integration/session-state-upgrade.test.ts',
      'src/integration/review-host-task-chain-e2e.test.ts',
      'src/integration/reviewer-contract-e2e.test.ts',
      'src/integration/tools/helpers.test.ts',
      'src/integration/tools/audit-outbox.test.ts',
      'src/integration/tools/write-state-with-artifacts.test.ts',
      'src/integration/plugin-compaction.test.ts',
      'src/integration/plugin-enforcement-tracking.test.ts',
      'src/integration/plugin-events.test.ts',
      'src/integration/plugin-helpers.test.ts',
      'src/integration/plugin-host-task-diagnostics-helpers.test.ts',
      'src/integration/plugin-logging.test.ts',
      'src/integration/plugin-orchestrator-arch-ssot.test.ts',
      'src/integration/plugin-orchestrator-bug16.test.ts',
      'src/integration/plugin-orchestrator-exhaustion.test.ts',
      'src/integration/plugin-orchestrator-independent-review.test.ts',
      'src/integration/plugin-orchestrator-plan-ssot.test.ts',
      'src/integration/plugin-orchestrator-review-content.test.ts',
      'src/integration/plugin-orchestrator-unable.test.ts',
      'src/integration/plugin-policy.test.ts',
      'src/integration/plugin-risk.test.ts',
      'src/integration/plugin-task-evidence.test.ts',
      'src/integration/plugin-workspace.test.ts',
      'src/integration/plugin-workspace-semantic-outbox.test.ts',
      // Added with the trust-boundary scope extension: these suites are the
      // covering tests for newly mutated authorities and must run, otherwise
      // those files would be mutated without any test able to kill a mutant.
      'src/integration/runtime-lease.test.ts',
      'src/integration/review/enforcement/challenge-binding.test.ts',
      'src/state/evidence-mutation-episode.test.ts',
    ],
    exclude: [
      'src/security/actions-pinning.test.ts',
      'src/architecture/__tests__/dependency-rules.test.ts',
      // Stryker executes vitest in worker threads, where Node does not
      // implement `process.chdir()`. This suite changes the working directory
      // per case and therefore aborts the whole mutation run before any mutant
      // is executed. It covers `adapters/gh-cli.ts`, which is not in the
      // mutation scope, so excluding it costs no mutation coverage.
      'src/adapters/gh-cli-branch-base.test.ts',
      // This invokes compiled dist hooks, not the mutated source modules. A
      // fresh production build is outside the Stryker workspace lifecycle.
      'src/hooks/command-hooks-smoke.test.ts',
      'src/__fixtures__.ts',
      'src/integration/test-helpers.ts',
      'src/audit/audit-test-helpers.ts',
      'src/test-policy.ts',
    ],
    globals: false,
    testTimeout: 60_000,
  },
});
