/**
 * @module integration/tools/review-validation-byte-envelopes.test
 * @description Byte-exact comparison of the review-validation blocked envelopes
 * against the reference captured from the pre-refactor implementation at
 * `1c4485e8`.
 *
 * The fixture was generated by running the same scenario corpus
 * (`review-validation-byte-test-fixtures.ts`) against the base implementation
 * and persisting the exact serialized strings. Field order, recovery texts,
 * optional fields, and failure precedence are therefore pinned byte for byte.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import type {
  StructuredFindingsResolution,
  StructuredResolutionDiagnostics,
} from '../review/validation/review-validation-structured-evidence.js';
import {
  formatReviewValidationFailure,
  structuredResolutionFailure,
} from '../review/validation/review-validation-failure.js';
import {
  resolveStructuredEffectiveFindings,
  validateReviewFindings,
} from '../review/validation/review-validation.js';
import { hashFindings } from '../review/findings-hash.js';
import { buildByteCorpus } from './review-validation-byte-test-fixtures.js';

interface ByteEnvelopeFixture {
  readonly validation: Readonly<Record<string, string>>;
  readonly resolution: Readonly<Record<string, string>>;
  readonly effective: Readonly<Record<string, string>>;
}

const FIXTURE_PATH = join(
  process.cwd(),
  'src/integration/tools/__fixtures__/review-validation-byte-envelopes.json',
);

const logger = { warn: () => {} };

function loadFixture(): ByteEnvelopeFixture {
  return JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as ByteEnvelopeFixture;
}

describe('review validation byte-exact envelopes (base 1c4485e8)', () => {
  const corpus = buildByteCorpus(hashFindings);
  const fixture = loadFixture();

  it('covers exactly the same scenario set as the base capture', () => {
    expect(Object.keys(fixture.validation).sort()).toEqual(
      corpus.validation.map((scenario) => scenario.id).sort(),
    );
    expect(Object.keys(fixture.resolution).sort()).toEqual(
      corpus.resolution.map((scenario) => scenario.id).sort(),
    );
    expect(Object.keys(fixture.effective).sort()).toEqual(
      corpus.effective.map((scenario) => scenario.id).sort(),
    );
  });

  for (const scenario of corpus.validation) {
    it(`validation: ${scenario.id}`, () => {
      const failure = validateReviewFindings(
        scenario.findings,
        scenario.ctx as Parameters<typeof validateReviewFindings>[1],
      );
      expect(failure).not.toBeNull();
      if (failure === null) return;
      expect(failure.code, `${scenario.id} reaches its intended path`).toBe(scenario.expectedCode);
      expect(formatReviewValidationFailure(logger, failure)).toBe(fixture.validation[scenario.id]);
    });
  }

  for (const scenario of corpus.resolution) {
    it(`resolution: ${scenario.id}`, () => {
      const resolution = scenario.resolution as unknown as Exclude<
        StructuredFindingsResolution,
        { kind: 'resolved' }
      >;
      const diagnostics = scenario.diagnostics as unknown as StructuredResolutionDiagnostics[];
      const failure = structuredResolutionFailure(resolution, diagnostics);
      expect(failure.code, `${scenario.id} maps to its intended code`).toBe(scenario.expectedCode);
      expect(formatReviewValidationFailure(logger, failure)).toBe(fixture.resolution[scenario.id]);
    });
  }

  for (const scenario of corpus.effective) {
    it(`effective: ${scenario.id}`, () => {
      const result = resolveStructuredEffectiveFindings(
        scenario.ctx as unknown as Parameters<typeof resolveStructuredEffectiveFindings>[0],
      );
      expect(result.kind).toBe('blocked');
      if (result.kind !== 'blocked') return;
      expect(result.failure.code, `${scenario.id} maps to its intended code`).toBe(
        scenario.expectedCode,
      );
      expect(formatReviewValidationFailure(logger, result.failure)).toBe(
        fixture.effective[scenario.id],
      );
    });
  }
});
