import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { claudeCodePluginFiles } from './templates.js';
import { uninstallClaudeCodePlugin } from './platform-uninstall.js';

function writeTree(root: string, files: Record<string, string>): void {
  for (const [relativePath, content] of Object.entries(files)) {
    const path = join(root, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}

describe('platform uninstall ownership', () => {
  it('removes an exact Claude plugin tree generated by FlowGuard', async () => {
    const target = mkdtempSync(join(tmpdir(), 'fg-claude-exact-'));
    const pluginRoot = join(target, 'flowguard-plugin');
    try {
      writeTree(pluginRoot, claudeCodePluginFiles('1.2.3'));
      const result = await uninstallClaudeCodePlugin(target);
      expect(result).toEqual([expect.objectContaining({ path: pluginRoot, action: 'removed' })]);
      expect(() => readFileSync(join(pluginRoot, '.claude-plugin/plugin.json'))).toThrow();
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });

  it('preserves a modified same-named Claude plugin tree', async () => {
    const target = mkdtempSync(join(tmpdir(), 'fg-claude-modified-'));
    const pluginRoot = join(target, 'flowguard-plugin');
    try {
      writeTree(pluginRoot, claudeCodePluginFiles('1.2.3'));
      const skillPath = join(pluginRoot, 'skills/start/SKILL.md');
      writeFileSync(skillPath, '# customer modification\n');
      const result = await uninstallClaudeCodePlugin(target);
      expect(result).toEqual([
        expect.objectContaining({ action: 'skipped', reason: expect.stringContaining('differs') }),
      ]);
      expect(readFileSync(skillPath, 'utf-8')).toBe('# customer modification\n');
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });

  it('preserves a plugin tree with extra customer files', async () => {
    const target = mkdtempSync(join(tmpdir(), 'fg-claude-extra-'));
    const pluginRoot = join(target, 'flowguard-plugin');
    try {
      writeTree(pluginRoot, claudeCodePluginFiles('1.2.3'));
      writeFileSync(join(pluginRoot, 'customer-note.txt'), 'keep me');
      const result = await uninstallClaudeCodePlugin(target);
      expect(result[0]).toMatchObject({ action: 'skipped' });
      expect(readFileSync(join(pluginRoot, 'customer-note.txt'), 'utf-8')).toBe('keep me');
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });
});
