/**
 * @module mcp-server/mcp-schema-strictness.test
 * @description Runtime conformance guard for issue #565.
 *
 * Connects the REAL FlowGuard MCP server in-process (InMemoryTransport) and
 * inspects the JSON Schemas it actually publishes via `tools/list`. Asserts that
 * every tool's input schema declares `additionalProperties: false` so that
 * MCP hosts honoring `strict` reject unknown keys (e.g. a stray `reviewVerdict`
 * on an empty `flowguard_implement` record).
 *
 * This closes the gap where `.sdk-baselines/mcp/*.json` PINNED
 * `additionalProperties: false` but nothing verified the LIVE runtime matched —
 * the schema is generated by the MCP SDK from the Zod input schema, so the only
 * trustworthy assertion is against the live `tools/list` output.
 *
 * @test-policy HAPPY, EDGE — strictness present for all tools; verdict-bearing
 *   tool surfaces optional (not required) verdict args under strict mode.
 * @see https://github.com/koeppben23/governed-runtime/issues/565
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { createMcpServer } from './server.js';

interface ListedTool {
  readonly name: string;
  readonly inputSchema: {
    readonly type?: string;
    readonly additionalProperties?: unknown;
    readonly required?: readonly string[];
    readonly properties?: Record<string, unknown>;
  };
}

describe('MCP schema strictness (issue #565)', () => {
  let client: Client;
  let tools: ListedTool[];

  beforeAll(async () => {
    const server = createMcpServer();
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    client = new Client({ name: 'strictness-test', version: '0.0.0' });
    await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
    const listed = await client.listTools();
    tools = listed.tools as unknown as ListedTool[];
  });

  afterAll(async () => {
    await client.close();
  });

  it('HAPPY: lists all 16 governance tools', () => {
    expect(tools).toHaveLength(16);
  });

  describe('EDGE: every tool input schema forbids unknown keys', () => {
    it('all tools declare additionalProperties: false', () => {
      const offenders = tools
        .filter((t) => t.inputSchema.additionalProperties !== false)
        .map((t) => `${t.name}=${JSON.stringify(t.inputSchema.additionalProperties)}`);
      expect(
        offenders,
        `Tools whose live MCP schema is not strict (additionalProperties !== false): ${offenders.join(', ')}`,
      ).toEqual([]);
    });
  });

  it('EDGE: strict mode does not force optional args to be required', () => {
    // flowguard_implement carries only optional args (reviewVerdict, etc.).
    // Strict mode must reject UNKNOWN keys without marking declared keys required.
    const implement = tools.find((t) => t.name === 'flowguard_implement');
    expect(implement, 'flowguard_implement missing').toBeDefined();
    expect(implement!.inputSchema.additionalProperties).toBe(false);
    expect(implement!.inputSchema.required ?? []).toEqual([]);
  });
});
