/**
 * Golden Assertion Provider Conformance Tests
 *
 * Each test feeds a real frozen report artifact (generated by the actual
 * tool at a pinned version) through the production extraction pipeline:
 * collector → parser → codec → AssertionExtractionResult.
 *
 * These tests run without any network or toolchain dependency — they only
 * need the checked-in fixture files.
 *
 * toolchain provenance:
 *   JUnit: Maven Surefire 3.5.2 + JUnit Jupiter 5.11.4 (Java 21)
 *   Vitest: vitest 3.2.7 (Node 26)
 *   Jest:   jest 29.7.0 (Node 26)
 *   pytest: pytest 8.4.2 + pytest-json-report 1.5.0 (Python 3.14)
 *   Go:     go test -json (Go 1.26.5)
 */

import { describe, expect, it, beforeAll } from 'vitest';
import { readFileSync } from 'node:fs';
import { mkdtemp, rm, writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { randomUUID } from 'node:crypto';

import { completeAssertionExtraction } from '../../../src/verification/assertion-extractor.js';
import { takeSnapshot } from '../../../src/verification/verification-execution.js';
import {
  PARSER_BY_FORMAT,
  ASSERTION_CODEC_BY_PROVIDER,
  ASSERTION_FORMATS_BY_PROVIDER,
} from '../../../src/providers/registry.js';
import { CONFORMANCE_CASES, NEGATIVE_CASES } from './conformance-contract.js';
import type { AssertionProviderConformanceCase } from './conformance-contract.js';
import type {
  PreparedVerificationExecution,
  PreparedAssertionReportRunSpecific,
  PreparedAssertionReportSnapshotDiff,
  PreparedAssertionReportStdout,
} from '../../../src/verification/verification-execution.js';
import type { ExecutionEvidence } from '../../../src/verification/executor.js';
import type { ProviderId } from '../../../src/state/assertion-identity.js';
import type { AssertionExtractionResult } from '../../../src/state/evidence-validation.js';

const FIXTURE_ROOT = join(import.meta.dirname, 'fixtures');

function sha256(data: string): string {
  return createHash('sha256').update(data).digest('hex');
}

function loadFixture(relativePath: string): string {
  return readFileSync(join(FIXTURE_ROOT, relativePath), 'utf-8');
}

function makeEvidence(stdout: string): ExecutionEvidence {
  return {
    kind: 'test',
    command: '',
    exitCode: 0,
    passed: true,
    executionMs: 1,
    outputDigest: sha256(stdout),
    stdout,
    stderr: '',
    timedOut: false,
    startedAt: '2026-01-01T00:00:00.000Z',
  };
}

async function extractViaPipeline(
  c: AssertionProviderConformanceCase,
): Promise<AssertionExtractionResult> {
  const fixtureContent = loadFixture(c.fixture);
  const attemptId = randomUUID();
  const tmpDir = await mkdtemp(join(tmpdir(), 'fg-golden-'));

  try {
    let prepared: PreparedVerificationExecution;

    switch (c.collection) {
      case 'stdout': {
        prepared = {
          attemptId,
          kind: 'test',
          command: '',
          assertion: {
            capability: 'structured',
            report: {
              kind: 'stdout',
              spec: {
                collection: 'stdout',
                transport: 'stdout',
                format: c.format,
                providerId: c.providerId,
              },
            } satisfies PreparedAssertionReportStdout,
          },
        };
        const evidence = makeEvidence(fixtureContent);
        return await completeAssertionExtraction(prepared, evidence, tmpDir);
      }

      case 'run_specific': {
        const resultPattern = join(
          '.flowguard',
          'reports',
          attemptId,
          `report.${c.format === 'pytest_json' ? 'json' : c.format === 'vitest_json' ? 'json' : c.format === 'jest_json' ? 'json' : c.format}`,
        );
        const absResultPath = join(tmpDir, resultPattern);
        await mkdir(dirname(absResultPath), { recursive: true });
        await writeFile(absResultPath, fixtureContent, 'utf-8');

        prepared = {
          attemptId,
          kind: 'test',
          command: '',
          assertion: {
            capability: 'structured',
            report: {
              kind: 'run_specific',
              spec: {
                collection: 'run_specific',
                transport: 'file',
                format: c.format,
                providerId: c.providerId,
                outputArgumentTemplate: '',
                resultPatternTemplate: '',
              },
              resultPattern,
            } satisfies PreparedAssertionReportRunSpecific,
          },
        };
        const evidence = makeEvidence('');
        return await completeAssertionExtraction(prepared, evidence, tmpDir);
      }

      case 'snapshot_diff': {
        const standardPattern = 'target/surefire-reports/TEST-*.xml';
        const reportName = 'target/surefire-reports/TEST-report.xml';
        const absReportDir = join(tmpDir, 'target', 'surefire-reports');
        await mkdir(absReportDir, { recursive: true });
        await writeFile(join(tmpDir, reportName), fixtureContent, 'utf-8');

        prepared = {
          attemptId,
          kind: 'build',
          command: '',
          assertion: {
            capability: 'structured',
            report: {
              kind: 'snapshot_diff',
              spec: {
                collection: 'snapshot_diff',
                transport: 'file',
                format: c.format,
                providerId: c.providerId,
                standardPatterns: [standardPattern],
              },
              preExecutionSnapshot: [],
            } satisfies PreparedAssertionReportSnapshotDiff,
          },
        };
        const evidence = makeEvidence('');
        return await completeAssertionExtraction(prepared, evidence, tmpDir);
      }

      default:
        throw new Error(`unhandled collection: ${c.collection}`);
    }
  } finally {
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }
}

// ─── Per-case golden test ─────────────────────────────────────────────────

function testCase(c: AssertionProviderConformanceCase) {
  describe(`[${c.providerId}] ${c.id}`, () => {
    let result: AssertionExtractionResult;
    const fixtureContent = loadFixture(c.fixture);

    beforeAll(async () => {
      result = await extractViaPipeline(c);
    });

    it('extracts successfully through full pipeline', () => {
      expect(result.status).toBe('extracted');
    });

    it('has correct providerId, format, and binding', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        expect(result.providerId).toBe(c.providerId);
        expect(result.format).toBe(c.format);
        expect(result.bindingCapability).toBe(c.expected.bindingCapability);
      }
    });

    it('reportDigests match sha256 of fixture content', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        const expectedDigest = sha256(fixtureContent);
        for (const digest of result.reportDigests) {
          expect(digest).toBe(expectedDigest);
        }
      }
    });

    it('produces correct localId for every expected assertion', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        for (const expectedAssertion of c.expected.assertions) {
          const found = result.assertions.find(
            (a) => a.assertion.localId === expectedAssertion.localId,
          );
          expect(
            found,
            `missing assertion with localId: ${expectedAssertion.localId}`,
          ).toBeDefined();
          expect(found!.status).toBe(expectedAssertion.status);
          expect(found!.testName).toBe(expectedAssertion.testName);
          expect(found!.providerId).toBe(c.providerId);
          expect(found!.assertion.providerId).toBe(c.providerId);
          if (expectedAssertion.sourceFile !== undefined) {
            expect(found!.sourceFile).toBe(expectedAssertion.sourceFile);
          }
        }
      }
    });

    it('has no duplicate localIds', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        const ids = result.assertions.map((a) => a.assertion.localId);
        expect(new Set(ids).size).toBe(ids.length);
      }
    });

    it('produces correct summary', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        const summary = c.expected.summary;
        if (summary.assertionCount !== undefined) {
          expect(result.summary.assertionCount).toBe(summary.assertionCount);
        }
        if (summary.passedCount !== undefined) {
          expect(result.summary.passedCount).toBe(summary.passedCount);
        }
        if (summary.failedCount !== undefined) {
          expect(result.summary.failedCount).toBe(summary.failedCount);
        }
        if (summary.skippedCount !== undefined) {
          expect(result.summary.skippedCount).toBe(summary.skippedCount);
        }
        if (summary.erroredCount !== undefined) {
          expect(result.summary.erroredCount).toBe(summary.erroredCount);
        }
      }
    });

    it('summary counts sum to assertionCount', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        const s = result.summary;
        const total =
          s.passedCount + s.failedCount + s.erroredCount + s.skippedCount;
        expect(total).toBe(s.assertionCount);
      }
    });

    it('every assertion providerId matches extraction providerId', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        for (const a of result.assertions) {
          expect(a.providerId).toBe(c.providerId);
          expect(a.assertion.providerId).toBe(c.providerId);
        }
      }
    });

    it('every localId passes codec validation', () => {
      expect(result.status).toBe('extracted');
      if (result.status === 'extracted') {
        const codec = ASSERTION_CODEC_BY_PROVIDER.get(
          c.providerId as ProviderId,
        );
        expect(codec).toBeDefined();
        for (const a of result.assertions) {
          expect(
            codec!.validateLocalId(a.assertion.localId),
          ).toBe(true);
        }
      }
    });

    it('parse is deterministic', async () => {
      const second = await extractViaPipeline(c);
      if (result.status === 'extracted' && second.status === 'extracted') {
        expect(
          second.assertions.map((a) => a.assertion.localId),
        ).toEqual(result.assertions.map((a) => a.assertion.localId));
        expect(
          second.assertions.map((a) => a.status),
        ).toEqual(result.assertions.map((a) => a.status));
        expect(second.summary).toEqual(result.summary);
        expect(second.bindingCapability).toBe(result.bindingCapability);
        expect(second.reportDigests).toEqual(result.reportDigests);
      }
    });
  });
}

// ─── Negative cases ───────────────────────────────────────────────────────

async function extractNegative(
  providerId: string,
  format: string,
  fixture: string,
  collection: 'stdout' | 'run_specific',
): Promise<AssertionExtractionResult> {
  const fixtureContent = loadFixture(fixture);
  const attemptId = randomUUID();
  const tmpDir = await mkdtemp(join(tmpdir(), 'fg-golden-neg-'));

  try {
    let prepared: PreparedVerificationExecution;

    if (collection === 'stdout') {
      prepared = {
        attemptId,
        kind: 'test',
        command: '',
        assertion: {
          capability: 'structured',
          report: {
            kind: 'stdout',
            spec: {
              collection: 'stdout',
              transport: 'stdout',
              format,
              providerId,
            },
          } satisfies PreparedAssertionReportStdout,
        },
      };
      const evidence = makeEvidence(fixtureContent);
      return await completeAssertionExtraction(prepared, evidence, tmpDir);
    }

    const resultPattern = join('.flowguard', 'reports', attemptId, 'report');
    const absResultPath = join(tmpDir, resultPattern);
    await mkdir(dirname(absResultPath), { recursive: true });
    await writeFile(absResultPath, fixtureContent, 'utf-8');

    prepared = {
      attemptId,
      kind: 'test',
      command: '',
      assertion: {
        capability: 'structured',
        report: {
          kind: 'run_specific',
          spec: {
            collection: 'run_specific',
            transport: 'file',
            format,
            providerId,
            outputArgumentTemplate: '',
            resultPatternTemplate: '',
          },
          resultPattern,
        } satisfies PreparedAssertionReportRunSpecific,
      },
    };
    const evidence = makeEvidence('');
    return await completeAssertionExtraction(prepared, evidence, tmpDir);
  } finally {
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }
}

function testNegative(
  id: string,
  providerId: string,
  format: string,
  fixture: string,
  expectedStatus: string,
  expectedReasonCode: string,
) {
  it(`[${providerId}] ${id} → ${expectedStatus}/${expectedReasonCode}`, async () => {
    const collection = format === 'go_test_json' ? 'stdout' : 'run_specific';
    const result = await extractNegative(
      providerId,
      format,
      fixture,
      collection as 'stdout' | 'run_specific',
    );
    expect(result.status).toBe(expectedStatus);
    if ('reasonCode' in result) {
      expect(result.reasonCode).toBe(expectedReasonCode);
    }
  });
}

// ─── Suite ────────────────────────────────────────────────────────────────

describe('Golden Assertion Provider Conformance', () => {
  for (const c of CONFORMANCE_CASES) {
    testCase(c);
  }

  describe('Negative cases', () => {
    for (const nc of NEGATIVE_CASES) {
      testNegative(
        nc.id,
        nc.providerId,
        nc.format,
        nc.fixture,
        nc.expectedStatus,
        nc.expectedReasonCode,
      );
    }
  });

  describe('Registry contract', () => {
    it('every assertion-binding provider has at least one conformance case', () => {
      for (const [
        providerId,
        bindingFormats,
      ] of ASSERTION_FORMATS_BY_PROVIDER) {
        if (bindingFormats.size === 0) continue;
        const hasCase = CONFORMANCE_CASES.some(
          (c) => c.providerId === providerId,
        );
        expect(
          hasCase,
          `provider '${providerId}' has assertion-binding formats but no conformance case`,
        ).toBe(true);
      }
    });

    it('every parser in PARSER_BY_FORMAT has at least one conformance case', () => {
      for (const [format] of PARSER_BY_FORMAT) {
        const hasCase = CONFORMANCE_CASES.some((c) => c.format === format);
        expect(
          hasCase,
          `format '${format}' has a registered parser but no conformance case`,
        ).toBe(true);
      }
    });

    it('all three collection strategies are represented', () => {
      const strategies = new Set(CONFORMANCE_CASES.map((c) => c.collection));
      expect(strategies.has('run_specific')).toBe(true);
      expect(strategies.has('snapshot_diff')).toBe(true);
      expect(strategies.has('stdout')).toBe(true);
    });
  });
});
