/**
 * Golden Assertion Provider Conformance Tests
 *
 * Each test feeds a real frozen report artifact (generated by the actual
 * tool at a pinned version) through the production parser and validates
 * every structured field: localId, status, testName, binding capability,
 * and summary invariants.
 *
 * These tests run without any network or toolchain dependency — they only
 * need the checked-in fixture files.
 *
 * toolchain provenance:
 *   JUnit: Maven Surefire 3.5.2 + JUnit Jupiter 5.11.4 (Java 21)
 *   Vitest: vitest 3.2.7 (Node 26)
 *   Jest:   jest 29.7.0 (Node 26)
 *   pytest: pytest 8.4.2 + pytest-json-report 1.5.0 (Python 3.14)
 *   Go:     go test -json (Go 1.26.5)
 */

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { parseJUnitXml } from '../../../src/verification/assertion-parsers/junit-xml.js';
import { parseVitestJson } from '../../../src/verification/assertion-parsers/vitest-json.js';
import { parseJestJson } from '../../../src/verification/assertion-parsers/jest-json.js';
import { parsePytestJson } from '../../../src/verification/assertion-parsers/pytest-json.js';
import { parseGoTestJson } from '../../../src/verification/assertion-parsers/go-test-json.js';
import {
  PARSER_BY_FORMAT,
  ASSERTION_CODEC_BY_PROVIDER,
  ASSERTION_FORMATS_BY_PROVIDER,
} from '../../../src/verification/assertion-parsers/registry.js';
import { CONFORMANCE_CASES, NEGATIVE_CASES } from './conformance-contract.js';
import type { AssertionProviderConformanceCase } from './conformance-contract.js';
import type { ProviderId } from '../../../src/state/assertion-identity.js';
import type { ParseContext, ParserResult } from '../../../src/verification/assertion-parsers/types.js';

const FIXTURE_ROOT = join(import.meta.dirname, 'fixtures');

function sha256(data: string): string {
  return createHash('sha256').update(data).digest('hex');
}

function loadFixture(relativePath: string): string {
  return readFileSync(join(FIXTURE_ROOT, relativePath), 'utf-8');
}

function parseFixture(
  format: string,
  content: string,
  providerId: string,
): ParserResult {
  const ctx: ParseContext = { providerId: providerId as ProviderId };
  switch (format) {
    case 'junit_xml':
      return parseJUnitXml(content, 'test.xml', ctx);
    case 'vitest_json':
      return parseVitestJson(content, ctx);
    case 'jest_json':
      return parseJestJson(content, ctx);
    case 'pytest_json':
      return parsePytestJson(content, ctx);
    case 'go_test_json':
      return parseGoTestJson(content, ctx);
    default:
      throw new Error(`unknown format: ${format}`);
  }
}

// ─── Per-case golden test ─────────────────────────────────────────────────

function testCase(c: AssertionProviderConformanceCase) {
  describe(`[${c.providerId}] ${c.id}`, () => {
    const fixtureContent = loadFixture(c.fixture);
    const fixtureDigest = sha256(fixtureContent);

    let result: ParserResult;

    it('parses successfully', () => {
      result = parseFixture(c.format, fixtureContent, c.providerId);
      expect(result.assertions.length).toBe(c.expected.assertions.length);
    });

    it('produces correct localId for every assertion', () => {
      for (const expectedAssertion of c.expected.assertions) {
        const found = result.assertions.find(
          (a) => a.assertion.localId === expectedAssertion.localId,
        );
        expect(
          found,
          `missing assertion with localId: ${expectedAssertion.localId}`,
        ).toBeDefined();
        expect(found!.status).toBe(expectedAssertion.status);
        expect(found!.testName).toBe(expectedAssertion.testName);
        expect(found!.providerId).toBe(c.providerId);
        expect(found!.assertion.providerId).toBe(c.providerId);
        if (expectedAssertion.sourceFile !== undefined) {
          expect(found!.sourceFile).toBe(expectedAssertion.sourceFile);
        }
      }
    });

    it('has no duplicate localIds', () => {
      const ids = result.assertions.map((a) => a.assertion.localId);
      expect(new Set(ids).size).toBe(ids.length);
    });

    it('produces correct summary', () => {
      const summary = c.expected.summary;
      if (summary.assertionCount !== undefined) {
        expect(result.summary.assertionCount).toBe(summary.assertionCount);
      }
      if (summary.passedCount !== undefined) {
        expect(result.summary.passedCount).toBe(summary.passedCount);
      }
      if (summary.failedCount !== undefined) {
        expect(result.summary.failedCount).toBe(summary.failedCount);
      }
      if (summary.erroredCount !== undefined) {
        expect(result.summary.erroredCount).toBe(summary.erroredCount);
      }
      if (summary.skippedCount !== undefined) {
        expect(result.summary.skippedCount).toBe(summary.skippedCount);
      }
      if (summary.suiteInfrastructureError !== undefined) {
        expect(result.summary.suiteInfrastructureError).toBe(
          summary.suiteInfrastructureError,
        );
      }
    });

    it('summary counts sum to assertionCount', () => {
      const s = result.summary;
      const total =
        s.passedCount + s.failedCount + s.erroredCount + s.skippedCount;
      expect(total).toBe(s.assertionCount);
    });

    it('every assertion providerId matches extraction providerId', () => {
      for (const a of result.assertions) {
        expect(a.providerId).toBe(c.providerId);
        expect(a.assertion.providerId).toBe(c.providerId);
      }
    });

    it('every localId is non-empty', () => {
      for (const a of result.assertions) {
        expect(a.assertion.localId.length).toBeGreaterThan(0);
      }
    });

    it('every localId passes codec validation', () => {
      const codec = ASSERTION_CODEC_BY_PROVIDER.get(c.providerId as ProviderId);
      expect(codec, `no codec for provider ${c.providerId}`).toBeDefined();
      for (const a of result.assertions) {
        expect(
          codec!.validateLocalId(a.assertion.localId),
          `localId ${a.assertion.localId} failed codec validation for ${c.providerId}`,
        ).toBe(true);
      }
    });

    it('fixture digest matches sha256 of raw content', () => {
      expect(fixtureDigest).toBe(sha256(fixtureContent));
    });

    it('parse is deterministic', () => {
      const second = parseFixture(c.format, fixtureContent, c.providerId);
      expect(second.assertions.map((a) => a.assertion.localId)).toEqual(
        result.assertions.map((a) => a.assertion.localId),
      );
      expect(second.assertions.map((a) => a.status)).toEqual(
        result.assertions.map((a) => a.status),
      );
      expect(second.summary).toEqual(result.summary);
    });

    it('failed assertions have failure details when format supports it', () => {
      for (const expectedAssertion of c.expected.assertions) {
        if (expectedAssertion.status === 'failed') {
          const found = result.assertions.find(
            (a) => a.assertion.localId === expectedAssertion.localId,
          );
          if (found && c.format !== 'pytest_json') {
            // Some formats like Go may produce failures with messages
            expect(found!.status).toBe('failed');
          }
        }
      }
    });
  });
}

// ─── Negative cases ───────────────────────────────────────────────────────

function testNegative(
  id: string,
  providerId: string,
  format: string,
  fixture: string,
  expectedReasonCode: string,
) {
  it(`[${providerId}] ${id} → inconclusive/${expectedReasonCode}`, () => {
    const content = loadFixture(fixture);
    const result = parseFixture(format, content, providerId);
    expect(result.assertions).toHaveLength(0);
    expect(result.summary.assertionCount).toBe(0);
  });
}

// ─── Suite ────────────────────────────────────────────────────────────────

describe('Golden Assertion Provider Conformance', () => {
  for (const c of CONFORMANCE_CASES) {
    testCase(c);
  }

  describe('Negative cases', () => {
    for (const nc of NEGATIVE_CASES) {
      testNegative(
        nc.id,
        nc.providerId,
        nc.format,
        nc.fixture,
        nc.expectedReasonCode,
      );
    }
  });

  describe('Registry contract', () => {
    it('every assertion-binding provider has at least one conformance case', () => {
      for (const [providerId, bindingFormats] of ASSERTION_FORMATS_BY_PROVIDER) {
        // No need for providers with binding capabilities but no parser
        if (bindingFormats.size === 0) continue;
        const hasCase = CONFORMANCE_CASES.some(
          (c) => c.providerId === providerId,
        );
        expect(
          hasCase,
          `provider '${providerId}' has assertion-binding formats but no conformance case`,
        ).toBe(true);
      }
    });

    it('every parser in PARSER_BY_FORMAT has at least one conformance case', () => {
      for (const [format] of PARSER_BY_FORMAT) {
        const hasCase = CONFORMANCE_CASES.some((c) => c.format === format);
        expect(
          hasCase,
          `format '${format}' has a registered parser but no conformance case`,
        ).toBe(true);
      }
    });

    it('all three collection strategies are represented', () => {
      const strategies = new Set(CONFORMANCE_CASES.map((c) => c.collection));
      expect(strategies.has('run_specific')).toBe(true);
      expect(strategies.has('snapshot_diff')).toBe(true);
      expect(strategies.has('stdout')).toBe(true);
    });
  });
});
