/**
 * @module review
 * @description /review rail — review report generation and review flow.
 *
 * Two modes:
 *
 * 1. Report generator (executeReview): Pure read-only report generation.
 *    Always available, does NOT mutate state.
 *    Produces a ReviewReport with completeness matrix and findings.
 *
 * 2. Flow mode (executeReviewFlow): Standalone review flow.
 *    READY → REVIEW → REVIEW_COMPLETE.
 *    Mutates state via state machine transitions.
 *    The report is generated by the tool layer after the rail returns.
 *
 * @version v2
 */

import type { SessionState } from '../state/schema.js';
import { ReviewReport, type ExternalReference, type InputOrigin } from '../state/evidence.js';
import { REVIEW_REPORT_SCHEMA_ID } from '../shared/flowguard-identifiers.js';
import { Command, isCommandAllowed } from '../machine/commands.js';
import { evaluateCompleteness } from '../audit/completeness.js';
import type { RailResult, RailContext, TransitionRecord, RailBlocked } from './types.js';
import { autoAdvance, applyTransition, createPolicyEvalFn } from './types.js';
import { blocked } from '../config/reasons.js';
import { hasGhCli, loadPrDiff, loadBranchDiff } from '../adapters/gh-cli.js';

// ─── Content Loading Helpers ──────────────────────────────────────

// ─── URL Validation (BUG-13: SSRF Mitigation) ───────────────────────

/** Private/reserved IPv4 CIDR ranges that must be blocked. */
const PRIVATE_IPV4_RANGES: Array<{ prefix: number; mask: number }> = [
  { prefix: 0x7f000000, mask: 0xff000000 }, // 127.0.0.0/8  (loopback)
  { prefix: 0x0a000000, mask: 0xff000000 }, // 10.0.0.0/8   (RFC 1918)
  { prefix: 0xac100000, mask: 0xfff00000 }, // 172.16.0.0/12 (RFC 1918)
  { prefix: 0xc0a80000, mask: 0xffff0000 }, // 192.168.0.0/16 (RFC 1918)
  { prefix: 0xa9fe0000, mask: 0xffff0000 }, // 169.254.0.0/16 (link-local)
  { prefix: 0x00000000, mask: 0xffffffff }, // 0.0.0.0/32    (unspecified)
];

/** Reserved IPv6 addresses that must be blocked. */
const PRIVATE_IPV6_PREFIXES = ['::1', 'fc00:', 'fd', 'fe80:'];

/**
 * Parse a dotted-decimal IPv4 string into a 32-bit integer.
 * Returns null if the string is not a valid IPv4 address.
 */
function parseIPv4(ip: string): number | null {
  const parts = ip.split('.');
  if (parts.length !== 4) return null;
  let result = 0;
  for (const part of parts) {
    // Reject non-decimal input such as hex; preserve existing leading-zero decimal behavior.
    if (!/^\d{1,3}$/.test(part)) return null;
    const n = Number(part);
    if (!Number.isInteger(n) || n < 0 || n > 255) return null;
    result = (result << 8) | n;
  }
  return result >>> 0; // unsigned 32-bit
}
export { parseIPv4 };

/**
 * Check if an IPv4 address (as 32-bit int) falls within any private/reserved range.
 */
function isPrivateIPv4(ip: number): boolean {
  return PRIVATE_IPV4_RANGES.some((range) => (ip & range.mask) >>> 0 === range.prefix >>> 0);
}

/**
 * Check if an IPv6 address string is private/reserved.
 * Covers: ::1 (loopback), fc00::/7 (unique-local), fe80::/10 (link-local).
 */
function isPrivateIPv6(ip: string): boolean {
  const normalized = ip.toLowerCase();
  return PRIVATE_IPV6_PREFIXES.some((prefix) => normalized.startsWith(prefix));
}

/**
 * Validate a URL for safe external fetch. Fail-closed: any parsing
 * failure or disallowed target results in rejection.
 *
 * Rules:
 * - Scheme must be `https:` (no http, file, ftp, data, etc.)
 * - Hostname must not resolve to private/reserved IP ranges
 * - Hostname must not be `localhost` or a bare IPv4/IPv6 loopback
 * - URL must parse successfully via `new URL()`
 *
 * @returns Object with `valid` flag and optional `reason` for rejection.
 */
export function validateReviewUrl(url: string): { valid: true } | { valid: false; reason: string } {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return { valid: false, reason: `URL parsing failed: ${url}` };
  }

  // Scheme allowlist: only HTTPS
  if (parsed.protocol !== 'https:') {
    return {
      valid: false,
      reason: `URL scheme '${parsed.protocol}' is not allowed; only https: is permitted`,
    };
  }

  const hostname = parsed.hostname.toLowerCase();

  // Block localhost (any casing)
  if (hostname === 'localhost') {
    return { valid: false, reason: 'URL hostname "localhost" is blocked (private network)' };
  }

  // Block bare IPv4 in private ranges
  // Hostname may be a bare IP or bracket-wrapped IPv6.
  const ipv4 = parseIPv4(hostname);
  if (ipv4 !== null) {
    if (isPrivateIPv4(ipv4)) {
      return {
        valid: false,
        reason: `URL hostname "${hostname}" resolves to a private/reserved IPv4 range`,
      };
    }
  }

  // Block bracket-wrapped IPv6 — URL parser keeps brackets in hostname.
  // e.g. new URL('https://[::1]/') → hostname = '[::1]'
  // Strip brackets before checking against private IPv6 prefixes.
  if (hostname.startsWith('[') && hostname.endsWith(']')) {
    const bareIpv6 = hostname.slice(1, -1);
    if (isPrivateIPv6(bareIpv6)) {
      return {
        valid: false,
        reason: `URL hostname "${hostname}" resolves to a private/reserved IPv6 range`,
      };
    }
  } else if (hostname.includes(':')) {
    // Bare IPv6 without brackets (unusual but defensive)
    if (isPrivateIPv6(hostname)) {
      return {
        valid: false,
        reason: `URL hostname "${hostname}" resolves to a private/reserved IPv6 range`,
      };
    }
  }

  return { valid: true };
}

/** Fetch content from URL using native fetch. Validates URL before fetching.
 *  Rejects private/reserved targets (SSRF mitigation).
 *  Disables redirect following to prevent SSRF via redirect.
 *  Throws on validation failure or HTTP errors. */
async function fetchUrlContent(url: string): Promise<string> {
  const validation = validateReviewUrl(url);
  if (!validation.valid) {
    throw new Error(`URL validation blocked: ${validation.reason}`);
  }
  const resp = await fetch(url, { redirect: 'error', signal: AbortSignal.timeout(15000) });
  if (!resp.ok) {
    throw new Error(`Failed to fetch ${url}: HTTP ${resp.status} ${resp.statusText}`);
  }
  return resp.text();
}

// ─── Executor Interface ───────────────────────────────────────────────

export interface ReviewExecutors {
  /**
   * Generate analysis findings via LLM. Optional.
   * If not provided, only mechanical checks are included in the report.
   *
   * @param state - Current session state
   * @param content - Optional external content (text blob, PR diff, branch diff, URL content)
   */
  analyze?: (
    state: SessionState,
    content?: string,
  ) => Promise<
    Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }>
  >;
}

// ─── Review Reference Input ───────────────────────────────────────────

export interface ReviewReferenceInput {
  readonly inputOrigin?: InputOrigin;
  readonly references?: ExternalReference[];
  /** Direct text blob for content analysis. */
  readonly text?: string;
  /** GitHub PR number — requires `gh` CLI. */
  readonly prNumber?: number;
  /** Git branch name — requires `gh` CLI. */
  readonly branch?: string;
  /** URL to fetch content from. */
  readonly url?: string;
  /** Skip external content loading (when analysisFindings provided by subagent). */
  readonly skipExternalContentLoad?: boolean;
}

// ─── Mechanical Findings ──────────────────────────────────────

function buildMechanicalFindings(
  state: SessionState,
  completeness: ReturnType<typeof evaluateCompleteness>,
): Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }> {
  const findings: Array<{
    severity: 'info' | 'warning' | 'error';
    category: string;
    message: string;
  }> = [];

  if (!state.ticket) {
    findings.push({ severity: 'warning', category: 'completeness', message: 'No ticket evidence' });
  }
  if (!state.plan) {
    findings.push({ severity: 'warning', category: 'completeness', message: 'No plan evidence' });
  }
  if (state.error) {
    findings.push({
      severity: 'error',
      category: 'error',
      message: `Error: ${state.error.code} — ${state.error.message}`,
    });
  }
  if (state.validation.some((v) => !v.passed)) {
    const failed = state.validation.filter((v) => !v.passed).map((v) => v.checkId);
    findings.push({
      severity: 'error',
      category: 'validation',
      message: `Failed checks: ${failed.join(', ')}`,
    });
  }

  if (completeness.fourEyes.required && !completeness.fourEyes.satisfied) {
    if (completeness.fourEyes.decidedBy === null) {
      findings.push({
        severity: 'warning',
        category: 'four-eyes',
        message: 'Four-eyes principle required but no review decision recorded yet',
      });
    } else {
      findings.push({
        severity: 'error',
        category: 'four-eyes',
        message: `Four-eyes principle VIOLATED: initiator (${completeness.fourEyes.initiatedBy}) and reviewer (${completeness.fourEyes.decidedBy}) are the same person`,
      });
    }
  }

  for (const slot of completeness.slots) {
    if (slot.status === 'missing') {
      findings.push({
        severity: 'warning',
        category: 'completeness',
        message: `${slot.label} is missing (required at phase ${state.phase})`,
      });
    } else if (slot.status === 'failed') {
      findings.push({
        severity: 'error',
        category: 'completeness',
        message: `${slot.label} has failed`,
      });
    }
  }

  return findings;
}

// ─── Load External Content ───────────────────────────────────

export async function loadExternalContent(
  refInput: ReviewReferenceInput,
): Promise<{ content: string } | RailBlocked> {
  if (refInput.prNumber !== undefined) return loadPrContent(refInput.prNumber);
  if (refInput.branch !== undefined) return loadBranchContent(refInput.branch);
  if (refInput.url !== undefined) return loadUrlContent(refInput);
  if (refInput.text !== undefined) return { content: refInput.text };
  return { content: '' };
}

function loadContentViaGh(
  fetcher: () => string,
  failureReasonPrefix: string,
): { content: string } | RailBlocked {
  if (!hasGhCli()) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: 'GitHub CLI (gh) is required. Install: https://cli.github.com/',
    });
  }
  try {
    return { content: fetcher() };
  } catch (err) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: `${failureReasonPrefix}: ${err instanceof Error ? err.message : String(err)}`,
    });
  }
}

function loadPrContent(prNumber: number): { content: string } | RailBlocked {
  return loadContentViaGh(() => loadPrDiff(prNumber), `Failed to load PR #${prNumber}`);
}

function loadBranchContent(branch: string): { content: string } | RailBlocked {
  return loadContentViaGh(() => loadBranchDiff(branch), `Failed to load branch '${branch}'`);
}

async function loadUrlContent(
  refInput: ReviewReferenceInput,
): Promise<{ content: string } | RailBlocked> {
  // BUG-13: Validate URL before fetch to block SSRF attempts with a clear reason.
  const validation = validateReviewUrl(refInput.url!);
  if (!validation.valid) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: `URL blocked: ${validation.reason}`,
    });
  }
  try {
    const content = await fetchUrlContent(refInput.url!);
    return { content };
  } catch (err) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: `Failed to fetch URL ${refInput.url}: ${err instanceof Error ? err.message : String(err)}`,
    });
  }
}

// ─── Build Report ──────────────────────────────────────────

interface BuildReportOptions {
  state: SessionState;
  now: string;
  validationSummary: Array<{ checkId: string; passed: boolean; detail: string }>;
  findings: Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }>;
  completeness: ReturnType<typeof evaluateCompleteness>;
  refInput?: ReviewReferenceInput;
}

export function buildReviewReport(opts: BuildReportOptions): ReviewReport {
  const { state, now, validationSummary, findings, completeness, refInput } = opts;
  const overallStatus = computeOverallStatus(findings);
  const refs = computeRefs(refInput);
  return ReviewReport.parse({
    schemaVersion: REVIEW_REPORT_SCHEMA_ID,
    sessionId: state.id,
    generatedAt: now,
    phase: state.phase,
    planDigest: state.plan?.current.digest ?? null,
    implDigest: state.implementation?.digest ?? null,
    validationSummary,
    findings,
    overallStatus,
    completeness,
    ...(refInput?.inputOrigin !== undefined && { inputOrigin: refInput.inputOrigin }),
    ...(refs !== undefined && { references: refs }),
  });
}

function computeOverallStatus(
  findings: Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }>,
): 'issues' | 'clean' | 'warnings' {
  const hasErrors = findings.some((f) => f.severity === 'error');
  const hasWarnings = findings.some((f) => f.severity === 'warning');
  return hasErrors ? 'issues' : hasWarnings ? 'warnings' : 'clean';
}

function computeRefs(refInput?: ReviewReferenceInput): ExternalReference[] | undefined {
  return refInput?.references && refInput.references.length > 0 ? refInput.references : undefined;
}

// ─── Report Generator ─────────────────────────────────────────

export async function executeReview(
  state: SessionState,
  now: string,
  executors?: ReviewExecutors,
  refInput?: ReviewReferenceInput,
): Promise<ReviewReport | RailBlocked> {
  const validationSummary = state.validation.map((v) => ({
    checkId: v.checkId,
    passed: v.passed,
    detail: v.detail,
  }));

  const completeness = evaluateCompleteness(state);
  const findings = buildMechanicalFindings(state, completeness);

  let externalContent: string | undefined;
  if (refInput && !refInput.skipExternalContentLoad) {
    const result = await loadExternalContent(refInput);
    if ('content' in result) {
      // Treat empty string as no content
      externalContent = result.content || undefined;
    } else {
      return result; // BLOCKED
    }
  }

  if (executors?.analyze) {
    const llmFindings = await executors.analyze(state, externalContent);
    findings.push(...llmFindings);
  }

  return buildReviewReport({
    state,
    now,
    validationSummary,
    findings,
    completeness,
    refInput,
  });
}

// ─── Review Flow Rail ─────────────────────────────────────────────────

/**
 * Transition from READY to REVIEW phase.
 * Returns the REVIEW state WITHOUT auto-advancing to REVIEW_COMPLETE.
 * The caller should generate the review report, write it to disk,
 * set reviewReportPath on the state, and THEN call autoAdvance.
 *
 * Per P8b: the reviewDone guard requires reviewReportPath to be set,
 * which means the report must be written before autoAdvance runs.
 */
export function startReviewFlow(state: SessionState, ctx: RailContext): RailResult {
  if (!isCommandAllowed(state.phase, Command.REVIEW)) {
    return blocked('COMMAND_NOT_ALLOWED', {
      command: '/review',
      phase: state.phase,
    });
  }

  const preTransitions: TransitionRecord[] = [];
  const at = ctx.now();
  const tr: TransitionRecord = { from: 'READY', to: 'REVIEW', event: 'REVIEW_SELECTED', at };
  preTransitions.push(tr);

  const reviewState: SessionState = applyTransition(
    state,
    'READY',
    'REVIEW',
    'REVIEW_SELECTED',
    at,
  );

  return {
    kind: 'ok',
    state: reviewState,
    evalResult: { kind: 'pending', phase: 'REVIEW' },
    transitions: preTransitions,
  };
}

/**
 * Full review flow: READY → REVIEW → REVIEW_COMPLETE (with autoAdvance).
 * Used only by tests or callers that already have persisted report evidence
 * and intentionally pass a state with reviewReportPath set.
 * The tool layer must use startReviewFlow + writeReport + autoAdvance instead.
 */
export function executeReviewFlow(state: SessionState, ctx: RailContext): RailResult {
  if (!isCommandAllowed(state.phase, Command.REVIEW)) {
    return blocked('COMMAND_NOT_ALLOWED', {
      command: '/review',
      phase: state.phase,
    });
  }

  const preTransitions: TransitionRecord[] = [];
  const at = ctx.now();
  const tr: TransitionRecord = { from: 'READY', to: 'REVIEW', event: 'REVIEW_SELECTED', at };
  preTransitions.push(tr);

  const reviewState: SessionState = applyTransition(
    state,
    'READY',
    'REVIEW',
    'REVIEW_SELECTED',
    at,
  );

  const evalFn = createPolicyEvalFn(ctx);
  const {
    state: finalState,
    evalResult,
    transitions: advanceTransitions,
  } = autoAdvance(reviewState, evalFn, ctx);
  const transitions = [...preTransitions, ...advanceTransitions];

  return { kind: 'ok', state: finalState, evalResult, transitions };
}
