/**
 * @module review
 * @description /review rail — review report generation and review flow.
 *
 * Two modes:
 *
 * 1. Report generator (executeReview): Pure read-only report generation.
 *    Always available, does NOT mutate state.
 *    Produces a ReviewReport with completeness matrix and findings.
 *
 * 2. Flow mode (executeReviewFlow): Standalone review flow.
 *    READY → REVIEW → REVIEW_COMPLETE.
 *    Mutates state via state machine transitions.
 *    The report is generated by the tool layer after the rail returns.
 *
 * @version v2
 */

import type { SessionState } from '../state/schema.js';
import type { ReviewReport, ExternalReference, InputOrigin } from '../state/evidence.js';
import { Command, isCommandAllowed } from '../machine/commands.js';
import { evaluateCompleteness } from '../audit/completeness.js';
import type { RailResult, RailContext, TransitionRecord } from './types.js';
import { autoAdvance, applyTransition, createPolicyEvalFn } from './types.js';
import { blocked } from '../config/reasons.js';
import { hasGhCli, loadPrDiff, loadBranchDiff } from '../adapters/gh-cli.js';

// ─── Content Loading Helpers ──────────────────────────────────────

/** Fetch content from URL using native fetch. Throws on failure. */
async function fetchUrlContent(url: string): Promise<string> {
  const resp = await fetch(url, { redirect: 'follow', signal: AbortSignal.timeout(15000) });
  if (!resp.ok) {
    throw new Error(`Failed to fetch ${url}: HTTP ${resp.status} ${resp.statusText}`);
  }
  return resp.text();
}

// ─── Executor Interface ───────────────────────────────────────────────

export interface ReviewExecutors {
  /**
   * Generate analysis findings via LLM. Optional.
   * If not provided, only mechanical checks are included in the report.
   *
   * @param state - Current session state
   * @param content - Optional external content (text blob, PR diff, branch diff, URL content)
   */
  analyze?: (
    state: SessionState,
    content?: string,
  ) => Promise<
    Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }>
  >;
}

// ─── Review Reference Input ───────────────────────────────────────────

export interface ReviewReferenceInput {
  readonly inputOrigin?: InputOrigin;
  readonly references?: ExternalReference[];
  /** Direct text blob for content analysis. */
  readonly text?: string;
  /** GitHub PR number — requires `gh` CLI. */
  readonly prNumber?: number;
  /** Git branch name — requires `gh` CLI. */
  readonly branch?: string;
  /** URL to fetch content from. */
  readonly url?: string;
  /** Skip external content loading (when analysisFindings provided by subagent). */
  readonly skipExternalContentLoad?: boolean;
}

// ─── Mechanical Findings ──────────────────────────────────────

function buildMechanicalFindings(
  state: SessionState,
  completeness: ReturnType<typeof evaluateCompleteness>,
): Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }> {
  const findings: Array<{
    severity: 'info' | 'warning' | 'error';
    category: string;
    message: string;
  }> = [];

  if (!state.ticket) {
    findings.push({ severity: 'warning', category: 'completeness', message: 'No ticket evidence' });
  }
  if (!state.plan) {
    findings.push({ severity: 'warning', category: 'completeness', message: 'No plan evidence' });
  }
  if (state.error) {
    findings.push({
      severity: 'error',
      category: 'error',
      message: `Error: ${state.error.code} — ${state.error.message}`,
    });
  }
  if (state.validation.some((v) => !v.passed)) {
    const failed = state.validation.filter((v) => !v.passed).map((v) => v.checkId);
    findings.push({
      severity: 'error',
      category: 'validation',
      message: `Failed checks: ${failed.join(', ')}`,
    });
  }

  if (completeness.fourEyes.required && !completeness.fourEyes.satisfied) {
    if (completeness.fourEyes.decidedBy === null) {
      findings.push({
        severity: 'warning',
        category: 'four-eyes',
        message: 'Four-eyes principle required but no review decision recorded yet',
      });
    } else {
      findings.push({
        severity: 'error',
        category: 'four-eyes',
        message: `Four-eyes principle VIOLATED: initiator (${completeness.fourEyes.initiatedBy}) and reviewer (${completeness.fourEyes.decidedBy}) are the same person`,
      });
    }
  }

  for (const slot of completeness.slots) {
    if (slot.status === 'missing') {
      findings.push({
        severity: 'warning',
        category: 'completeness',
        message: `${slot.label} is missing (required at phase ${state.phase})`,
      });
    } else if (slot.status === 'failed') {
      findings.push({
        severity: 'error',
        category: 'completeness',
        message: `${slot.label} has failed`,
      });
    }
  }

  return findings;
}

// ─── Load External Content ───────────────────────────────────

export async function loadExternalContent(
  refInput: ReviewReferenceInput,
): Promise<{ content: string } | ReviewReport> {
  if (refInput.prNumber !== undefined) return loadPrContent(refInput);
  if (refInput.branch !== undefined) return loadBranchContent(refInput);
  if (refInput.url !== undefined) return loadUrlContent(refInput);
  if (refInput.text !== undefined) return { content: refInput.text };
  return { content: '' };
}

function loadPrContent(refInput: ReviewReferenceInput): { content: string } | ReviewReport {
  if (!hasGhCli()) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: 'GitHub CLI (gh) is required. Install: https://cli.github.com/',
    }) as unknown as ReviewReport;
  }
  try {
    return { content: loadPrDiff(refInput.prNumber!) };
  } catch (err) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: `Failed to load PR #${refInput.prNumber}: ${err instanceof Error ? err.message : String(err)}`,
    }) as unknown as ReviewReport;
  }
}

function loadBranchContent(refInput: ReviewReferenceInput): { content: string } | ReviewReport {
  if (!hasGhCli()) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: 'GitHub CLI (gh) is required. Install: https://cli.github.com/',
    }) as unknown as ReviewReport;
  }
  try {
    return { content: loadBranchDiff(refInput.branch!) };
  } catch (err) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: `Failed to load branch '${refInput.branch}': ${err instanceof Error ? err.message : String(err)}`,
    }) as unknown as ReviewReport;
  }
}

async function loadUrlContent(
  refInput: ReviewReferenceInput,
): Promise<{ content: string } | ReviewReport> {
  try {
    const content = await fetchUrlContent(refInput.url!);
    return { content };
  } catch (err) {
    return blocked('COMMAND_BLOCKED', {
      command: '/review',
      reason: `Failed to fetch URL ${refInput.url}: ${err instanceof Error ? err.message : String(err)}`,
    }) as unknown as ReviewReport;
  }
}

// ─── Build Report ──────────────────────────────────────────

interface BuildReportOptions {
  state: SessionState;
  now: string;
  validationSummary: Array<{ checkId: string; passed: boolean; detail: string }>;
  findings: Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }>;
  completeness: ReturnType<typeof evaluateCompleteness>;
  refInput?: ReviewReferenceInput;
}

function buildReport(opts: BuildReportOptions): ReviewReport {
  const { state, now, validationSummary, findings, completeness, refInput } = opts;
  const overallStatus = computeOverallStatus(findings);
  const refs = computeRefs(refInput);
  return {
    schemaVersion: 'flowguard-review-report.v1',
    sessionId: state.id,
    generatedAt: now,
    phase: state.phase,
    planDigest: state.plan?.current.digest ?? null,
    implDigest: state.implementation?.digest ?? null,
    validationSummary,
    findings,
    overallStatus,
    completeness,
    ...(refInput?.inputOrigin !== undefined && { inputOrigin: refInput.inputOrigin }),
    ...(refs !== undefined && { references: refs }),
  };
}

function computeOverallStatus(
  findings: Array<{ severity: 'info' | 'warning' | 'error'; category: string; message: string }>,
): 'issues' | 'clean' | 'warnings' {
  const hasErrors = findings.some((f) => f.severity === 'error');
  const hasWarnings = findings.some((f) => f.severity === 'warning');
  return hasErrors ? 'issues' : hasWarnings ? 'warnings' : 'clean';
}

function computeRefs(refInput?: ReviewReferenceInput): ExternalReference[] | undefined {
  return refInput?.references && refInput.references.length > 0 ? refInput.references : undefined;
}

// ─── Report Generator ─────────────────────────────────────────

export async function executeReview(
  state: SessionState,
  now: string,
  executors?: ReviewExecutors,
  refInput?: ReviewReferenceInput,
): Promise<ReviewReport> {
  const validationSummary = state.validation.map((v) => ({
    checkId: v.checkId,
    passed: v.passed,
    detail: v.detail,
  }));

  const completeness = evaluateCompleteness(state);
  const findings = buildMechanicalFindings(state, completeness);

  let externalContent: string | undefined;
  if (refInput && !refInput.skipExternalContentLoad) {
    const result = await loadExternalContent(refInput);
    if ('content' in result) {
      // Treat empty string as no content
      externalContent = result.content || undefined;
    } else {
      return result; // BLOCKED
    }
  }

  if (executors?.analyze) {
    const llmFindings = await executors.analyze(state, externalContent);
    findings.push(...llmFindings);
  }

  return buildReport({
    state,
    now,
    validationSummary,
    findings,
    completeness,
    refInput,
  });
}

// ─── Review Flow Rail ─────────────────────────────────────────────────

/**
 * Transition from READY to REVIEW phase.
 * Returns the REVIEW state WITHOUT auto-advancing to REVIEW_COMPLETE.
 * The caller should generate the review report, write it to disk,
 * set reviewReportPath on the state, and THEN call autoAdvance.
 *
 * Per P8b: the reviewDone guard requires reviewReportPath to be set,
 * which means the report must be written before autoAdvance runs.
 */
export function startReviewFlow(state: SessionState, ctx: RailContext): RailResult {
  if (!isCommandAllowed(state.phase, Command.REVIEW)) {
    return blocked('COMMAND_NOT_ALLOWED', {
      command: '/review',
      phase: state.phase,
    });
  }

  const preTransitions: TransitionRecord[] = [];
  const at = ctx.now();
  const tr: TransitionRecord = { from: 'READY', to: 'REVIEW', event: 'REVIEW_SELECTED', at };
  preTransitions.push(tr);

  const reviewState: SessionState = applyTransition(
    state,
    'READY',
    'REVIEW',
    'REVIEW_SELECTED',
    at,
  );

  return {
    kind: 'ok',
    state: reviewState,
    evalResult: { kind: 'pending', phase: 'REVIEW' },
    transitions: preTransitions,
  };
}

/**
 * Full review flow: READY → REVIEW → REVIEW_COMPLETE (with autoAdvance).
 * Used when reviewReportPath is already set before calling this function
 * (e.g. via the tool layer pre-setting it).
 */
export function executeReviewFlow(state: SessionState, ctx: RailContext): RailResult {
  if (!isCommandAllowed(state.phase, Command.REVIEW)) {
    return blocked('COMMAND_NOT_ALLOWED', {
      command: '/review',
      phase: state.phase,
    });
  }

  const preTransitions: TransitionRecord[] = [];
  const at = ctx.now();
  const tr: TransitionRecord = { from: 'READY', to: 'REVIEW', event: 'REVIEW_SELECTED', at };
  preTransitions.push(tr);

  const reviewState: SessionState = applyTransition(
    state,
    'READY',
    'REVIEW',
    'REVIEW_SELECTED',
    at,
  );

  const evalFn = createPolicyEvalFn(ctx);
  const {
    state: finalState,
    evalResult,
    transitions: advanceTransitions,
  } = autoAdvance(reviewState, evalFn, ctx);
  const transitions = [...preTransitions, ...advanceTransitions];

  return { kind: 'ok', state: finalState, evalResult, transitions };
}
