/**
 * @module integration/review/finding-relation-grammar
 * @description Deterministic, machine-consistent FindingRelation grammar for
 * reviewer prompts. Values are sourced from reviewer-contract.ts (the canonical SSOT),
 * which is verified against the Zod schemas by reviewer-contract.test.ts.
 * Every reviewer transport MUST receive this grammar so no path can guess the
 * schema that the other path enforces.
 */
export function renderFindingRelationGrammar(): string {
  return [
    '## Finding Output Contract',
    '',
    'Every material finding MUST include a structured relation:',
    '',
    '{',
    '  "severity": "critical" | "major" | "minor",',
    '  "category": "completeness" | "correctness" | "feasibility" | "risk" | "quality",',
    '  "message": "<specific defect description>",',
    '  "relation": {',
    '    "subjectAnchors": [ ... ],   // min 1, identifies what is criticized',
    '    "evidenceLocations": [ ... ]  // optional, repository evidence',
    '  }',
    '}',
    '',
    '### subjectAnchors',
    '',
    'Subject anchors identify what is being criticized. Use ONE of:',
    '',
    'repository_location (for file-level targets):',
    '{',
    '  "kind": "repository_location",',
    '  "location": {',
    '    "path": "<string>",',
    '    "revision": "base" | "head",',
    '    "line": <integer optional>,',
    '    "endLine": <integer optional>',
    '  }',
    '}',
    '',
    'artifact_section (for plan/ADR section targets):',
    '{',
    '  "kind": "artifact_section",',
    '  "artifactKind": "plan" | "adr",',
    '  "artifactDigest": "<string>",',
    '  "sectionPath": [{"headingDepth": <int 1-6>, "siblingIndex": <int >=1>, "headingText": "<string>"}]',
    '}',
    '',
    'content (for external content targets):',
    '{',
    '  "kind": "content",',
    '  "subjectDigest": "<string>",',
    '  "range": { "startLine": <int >=1>, "endLine": <int >=1 optional> }',
    '}',
    '',
    '### evidenceLocations (optional)',
    '',
    'Array of repository location entries. evidenceLocations MAY be empty.',
    'They support the finding with repository evidence but do not replace',
    'or expand the reviewed subject.',
    '',
    '### Revision Rules',
    '',
    'revision is a frozen alias, never a SHA.',
    'Only "base" or "head" are valid.',
  ].join('\n');
}
