import { describe, expect, it } from 'vitest';
import { deriveEventContract, normalize, sha256 } from '../sdk-type-snapshot.mjs';

const SDK_FIXTURE = [
  'export type Event = EventAlpha | EventBeta;',
  '',
  'export type EventAlpha = {',
  '    type: "alpha.created";',
  '    properties: {',
  '        id: string;',
  '    };',
  '};',
  '',
  'export type EventBeta = {',
  '    type: "beta.error";',
  '    properties: {',
  '        message?: string;',
  '    };',
  '};',
].join('\n');

describe('scripts/sdk-type-snapshot', () => {
  describe('normalize', () => {
    it('normalizes CRLF and trailing whitespace to a single trailing newline', () => {
      expect(normalize('a  \r\nb\r\n\r\n')).toBe('a\nb\n');
    });

    it('is idempotent', () => {
      const once = normalize('a\r\nb');
      expect(normalize(once)).toBe(once);
    });
  });

  describe('sha256', () => {
    it('is stable for identical content and differs for distinct content', () => {
      expect(sha256('x')).toBe(sha256('x'));
      expect(sha256('x')).not.toBe(sha256('y'));
    });
  });

  describe('deriveEventContract', () => {
    it('captures the union and every member declaration in union order', () => {
      const derived = deriveEventContract(SDK_FIXTURE);
      expect(derived).toContain('export type Event = EventAlpha | EventBeta;');
      expect(derived).toContain('type: "alpha.created";');
      expect(derived).toContain('type: "beta.error";');
      expect(derived.indexOf('EventAlpha = {')).toBeLessThan(derived.indexOf('EventBeta = {'));
      expect(derived).toContain('Generated by scripts/sdk-type-snapshot.mjs --update');
    });

    it('fails loudly when the Event union is missing', () => {
      expect(() => deriveEventContract('export type NotEvent = string;')).toThrow(/Event union/);
    });

    it('fails loudly when a union member declaration is missing', () => {
      const broken = [
        'export type Event = EventAlpha | EventMissing;',
        '',
        'export type EventAlpha = {',
        '    type: "alpha";',
        '};',
      ].join('\n');
      expect(() => deriveEventContract(broken)).toThrow(/EventMissing/);
    });
  });
});
