from pathlib import Path
import re


def read(path: str) -> str:
    return Path(path).read_text()


def write(path: str, content: str) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(content)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


# 1) Register the generation-mismatch reason emitted by the review pipelines.
path = "src/config/reasons-validation-review.ts"
text = read(path)
needle = """  {
    code: 'REVIEW_ATTEMPT_UNAVAILABLE',
    category: 'state',
    messageTemplate:
      'No bindable review attempt exists for obligation {obligationId}: {reason}. The frozen review material itself was not invalidated.',
    recoverySteps: [
      'Re-run flowguard_review with the original content fields and reviewObligationId to reissue a bindable attempt',
      'Pass the newly returned reviewerTaskPrompt VERBATIM to the reviewer Task; never reuse a previous prompt',
      'Do NOT submit reviewVerdict or reviewFindings to recover this state',
    ],
  },
"""
replacement = needle + """  {
    code: 'REVIEW_GENERATION_MISMATCH',
    category: 'state',
    messageTemplate:
      'The persisted review obligation does not match the active review criteria generation.',
    recoverySteps: [
      'Re-run the originating FlowGuard review transition to mint a fresh obligation under the active criteria generation',
      'Do not reuse findings or attempts whose criteria version or mandate digest belongs to an older generation',
      'If the mismatch persists, re-hydrate trusted session state and inspect the review-assurance audit trail',
    ],
  },
"""
text = replace_once(text, needle, replacement, "reason registry")
write(path, text)

# Keep the explicit split-count guard accurate.
path = "src/config/reasons-completeness.test.ts"
text = read(path)
text = replace_once(
    text,
    "it('all 288 codes from split arrays are registered exactly once (no duplicates)', async () => {",
    "it('all 292 codes from split arrays are registered exactly once (no duplicates)', async () => {",
    "reason-count title",
)
text = replace_once(text, "expect(allSplitCodes).toHaveLength(291);", "expect(allSplitCodes).toHaveLength(292);", "reason total")
text = replace_once(text, "expect(new Set(allSplitCodes).size).toBe(291);", "expect(new Set(allSplitCodes).size).toBe(292);", "reason unique total")
text = replace_once(text, "it('VALIDATION_REASONS has exactly 115 entries'", "it('VALIDATION_REASONS has exactly 116 entries'", "validation count title")
text = replace_once(text, "expect(VALIDATION_REASONS.length).toBe(115);", "expect(VALIDATION_REASONS.length).toBe(116);", "validation count")
write(path, text)

# 2) Update uninstall ownership tests to the intentional per-file ownership model.
write(
    "src/cli/platform-uninstall-ownership.test.ts",
    """import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { claudeCodePluginFiles } from './templates.js';
import { uninstallClaudeCodePlugin } from './platform-uninstall.js';

function writeTree(root: string, files: Record<string, string>): void {
  for (const [relativePath, content] of Object.entries(files)) {
    const path = join(root, relativePath);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
}

describe('platform uninstall ownership', () => {
  it('removes an exact Claude plugin tree generated by FlowGuard', async () => {
    const target = mkdtempSync(join(tmpdir(), 'fg-claude-exact-'));
    const pluginRoot = join(target, 'flowguard-plugin');
    try {
      writeTree(pluginRoot, claudeCodePluginFiles('1.2.3'));
      const result = await uninstallClaudeCodePlugin(target);
      expect(result.length).toBeGreaterThan(0);
      expect(result.every((operation) => operation.action === 'removed')).toBe(true);
      expect(existsSync(pluginRoot)).toBe(false);
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });

  it('preserves a modified managed file while removing unchanged FlowGuard-owned files', async () => {
    const target = mkdtempSync(join(tmpdir(), 'fg-claude-modified-'));
    const pluginRoot = join(target, 'flowguard-plugin');
    try {
      writeTree(pluginRoot, claudeCodePluginFiles('1.2.3'));
      const skillPath = join(pluginRoot, 'skills/start/SKILL.md');
      const unchangedManagedPath = join(pluginRoot, '.claude-plugin/plugin.json');
      writeFileSync(skillPath, '# customer modification\\n');

      const result = await uninstallClaudeCodePlugin(target);
      const modifiedOperation = result.find((operation) => operation.path === skillPath);

      expect(modifiedOperation).toMatchObject({
        action: 'skipped',
        reason: expect.stringContaining('ownership/content mismatch'),
      });
      expect(readFileSync(skillPath, 'utf-8')).toBe('# customer modification\\n');
      expect(existsSync(unchangedManagedPath)).toBe(false);
      expect(existsSync(pluginRoot)).toBe(true);
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });

  it('preserves extra customer files while removing FlowGuard-owned files', async () => {
    const target = mkdtempSync(join(tmpdir(), 'fg-claude-extra-'));
    const pluginRoot = join(target, 'flowguard-plugin');
    try {
      writeTree(pluginRoot, claudeCodePluginFiles('1.2.3'));
      const customerPath = join(pluginRoot, 'customer-note.txt');
      writeFileSync(customerPath, 'keep me');

      const result = await uninstallClaudeCodePlugin(target);

      expect(result.some((operation) => operation.action === 'removed')).toBe(true);
      expect(readFileSync(customerPath, 'utf-8')).toBe('keep me');
      expect(existsSync(pluginRoot)).toBe(true);
    } finally {
      rmSync(target, { recursive: true, force: true });
    }
  });
});
""",
)

# 3) Move SDK evidence persistence into a cohesive module. This keeps the shared
# helper below the production LOC budget and keeps each mutation function small.
shared_path = "src/integration/review/shared-helpers.ts"
shared = read(shared_path)
start_marker = "/**\n * Build SDK-session invocation evidence"
end_marker = "// ─── Invocation Helpers"
start = shared.find(start_marker)
end = shared.find(end_marker)
if start < 0 or end < 0 or end <= start:
    raise RuntimeError("shared helper evidence block markers not found")
shared = (
    shared[:start]
    + "export { recordEvidenceOrBlockReuse } from './sdk-evidence-recorder.js';\n\n"
    + shared[end:]
)
# Remove imports that were exclusively owned by the extracted block. Only drop a
# name when its sole remaining occurrence is the import itself.
for name in [
    "hasEvidenceReuse",
    "buildInvocationEvidence",
    "appendInvocationEvidence",
    "updateAttemptStatus",
]:
    if shared.count(name) == 1:
        shared = re.sub(rf"^  {name},\n", "", shared, count=1, flags=re.MULTILINE)
if shared.count("updateObligation") == 1:
    shared = re.sub(
        r"^import \{ updateObligation \} from './obligation-state\.js';\n",
        "",
        shared,
        count=1,
        flags=re.MULTILINE,
    )
if shared.count("ReviewObligationType") == 1:
    shared = re.sub(
        r"^import type \{ ReviewObligationType \} from '../../state/evidence\.js';\n",
        "",
        shared,
        count=1,
        flags=re.MULTILINE,
    )
if shared.count("EvidenceRecordResult") == 1:
    shared = re.sub(r"^  EvidenceRecordResult,\n", "", shared, count=1, flags=re.MULTILINE)
if shared.count("SemanticAuditIntent") == 1:
    shared = re.sub(
        r"^import type \{ SemanticAuditIntent \} from '../tools/audit-outbox\.js';\n",
        "",
        shared,
        count=1,
        flags=re.MULTILINE,
    )
if shared.count("SessionState") == 1:
    shared = re.sub(
        r"^import type \{ SessionState \} from '../../state/schema\.js';\n",
        "",
        shared,
        count=1,
        flags=re.MULTILINE,
    )
write(shared_path, shared)

write(
    "src/integration/review/sdk-evidence-recorder.ts",
    """/**
 * @module integration/review/sdk-evidence-recorder
 * @description Atomic persistence of SDK reviewer evidence and attempt lineage.
 */

import type { SessionState } from '../../state/schema.js';
import type { SemanticAuditIntent } from '../tools/audit-outbox.js';
import type { ReviewObligationType } from '../../state/evidence.js';
import type { ReviewerSuccessResult } from './orchestrator.js';
import {
  appendInvocationEvidence,
  buildInvocationEvidence,
  ensureReviewAssurance,
  hasEvidenceReuse,
  updateAttemptStatus,
} from './assurance.js';
import { updateObligation } from './obligation-state.js';
import type { EvidenceRecordResult, OrchestratorDeps } from './pipeline-types.js';
import { EVIDENCE_SOURCE_HOST, INVOCATION_MODE_SDK_SESSION } from './pipeline-types.js';

type SdkEvidenceParams = {
  obligationId: string;
  obligationType: ReviewObligationType;
  sessionId: string;
  childSessionId: string;
  attemptId: string;
  promptHash: string;
  findingsHash: string;
  invokedAt: string;
  fulfilledAt: string;
  reviewerResult: Pick<
    ReviewerSuccessResult,
    | 'sessionId'
    | 'reviewOutputMode'
    | 'structuredOutputUsed'
    | 'reviewAssuranceLevel'
    | 'extractionMethod'
    | 'modelCapabilityError'
    | 'findings'
  >;
  currentAssuranceInvocations: unknown[];
  semanticIntents?: (
    result: EvidenceRecordResult,
    state: SessionState,
    now: string,
  ) => readonly SemanticAuditIntent[];
};

type MutationFlags = {
  reused: boolean;
  missing: boolean;
  lineageUnavailable: boolean;
};

function buildSdkSessionInvocation(
  params: SdkEvidenceParams,
  obligation: { mandateDigest: string; criteriaVersion: string },
): ReturnType<typeof buildInvocationEvidence> {
  return buildInvocationEvidence({
    obligationId: params.obligationId,
    obligationType: params.obligationType,
    mandateDigest: obligation.mandateDigest,
    criteriaVersion: obligation.criteriaVersion,
    parentSessionId: params.sessionId,
    childSessionId: params.childSessionId,
    invocationMode: INVOCATION_MODE_SDK_SESSION,
    hostVisible: false,
    promptHash: params.promptHash,
    findingsHash: params.findingsHash,
    invokedAt: params.invokedAt,
    fulfilledAt: params.fulfilledAt,
    attemptId: params.attemptId,
    source: EVIDENCE_SOURCE_HOST,
    reviewOutputMode: params.reviewerResult.reviewOutputMode,
    structuredOutputUsed: params.reviewerResult.structuredOutputUsed,
    reviewAssuranceLevel: params.reviewerResult.reviewAssuranceLevel,
    extractionMethod: params.reviewerResult.extractionMethod,
    modelCapabilityError: params.reviewerResult.modelCapabilityError,
    capturedVerdict:
      params.reviewerResult.findings &&
      typeof params.reviewerResult.findings.overallVerdict === 'string'
        ? params.reviewerResult.findings.overallVerdict
        : undefined,
  });
}

function applyEvidenceMutation(
  state: SessionState,
  now: string,
  params: SdkEvidenceParams,
  flags: MutationFlags,
): SessionState {
  const assurance = ensureReviewAssurance(state.reviewAssurance);
  const obligation = assurance.obligations.find(
    (item) => item.obligationId === params.obligationId,
  );
  if (!obligation) {
    flags.missing = true;
    return state;
  }
  if (hasEvidenceReuse(assurance.invocations, params.childSessionId, params.findingsHash)) {
    flags.reused = true;
    return updateObligation(state, params.obligationId, (item) => ({
      ...item,
      status: 'blocked',
      blockedCode: 'SUBAGENT_EVIDENCE_REUSED',
    }));
  }
  const attempt = assurance.attempts.find((item) => item.attemptId === params.attemptId);
  const lineageMatches =
    attempt?.obligationId === obligation.obligationId &&
    attempt.obligationType === obligation.obligationType &&
    attempt.subjectDigest === obligation.subjectDigest &&
    attempt.status === 'created' &&
    attempt.childSessionId === undefined;
  if (!lineageMatches || !attempt) {
    flags.lineageUnavailable = true;
    return state;
  }

  const invocation = buildSdkSessionInvocation(params, obligation);
  const boundAssurance = updateAttemptStatus(
    assurance,
    attempt.attemptId,
    'bound',
    params.fulfilledAt,
    { childSessionId: params.childSessionId },
  );
  const withInvocation = {
    ...state,
    reviewAssurance: appendInvocationEvidence(boundAssurance, invocation),
  };
  return updateObligation(withInvocation, params.obligationId, (item) => ({
    ...item,
    status: 'fulfilled',
    invocationId: invocation.invocationId,
    fulfilledAt: now,
  }));
}

function resultFromFlags(flags: MutationFlags): EvidenceRecordResult {
  if (flags.missing) return 'missing';
  if (flags.lineageUnavailable) return 'lineage_unavailable';
  if (flags.reused) return 'reused';
  return 'fulfilled';
}

export async function recordEvidenceOrBlockReuse(
  deps: OrchestratorDeps,
  sessDir: string,
  params: SdkEvidenceParams,
): Promise<EvidenceRecordResult> {
  const flags: MutationFlags = { reused: false, missing: false, lineageUnavailable: false };
  await deps.updateReviewAssurance(
    sessDir,
    (state, now) => applyEvidenceMutation(state, now, params, flags),
    (state, now) => {
      const result = resultFromFlags(flags);
      return result === 'missing' || result === 'lineage_unavailable' || !params.semanticIntents
        ? []
        : params.semanticIntents(result, state, now);
    },
  );
  return resultFromFlags(flags);
}
""",
)

# 4) Reduce content-review complexity and function length without changing gates.
path = "src/integration/review/content-review-pipeline.ts"
text = read(path)
count_marker = """function countFindings(findings: unknown): number {
  return Array.isArray(findings) ? findings.length : Object.keys(findings ?? {}).length;
}
"""
generation_helper = count_marker + """
type PersistedReviewObligation = NonNullable<ReturnType<typeof findReviewObligationById>>;

function matchesActiveReviewGeneration(
  obligation: ReturnType<typeof findReviewObligationById>,
  reviewCtx: PipelineContext['reviewCtx'],
): obligation is PersistedReviewObligation {
  return (
    obligation !== undefined &&
    isCurrentReviewGeneration(obligation) &&
    obligation.criteriaVersion === reviewCtx.criteriaVersion &&
    obligation.mandateDigest === reviewCtx.mandateDigest
  );
}
"""
text = replace_once(text, count_marker, generation_helper, "content generation helper")
old_generation = """  if (
    !obligation ||
    !isCurrentReviewGeneration(obligation) ||
    obligation.criteriaVersion !== reviewCtx.criteriaVersion ||
    obligation.mandateDigest !== reviewCtx.mandateDigest
  ) {
"""
text = replace_once(
    text,
    old_generation,
    "  if (!matchesActiveReviewGeneration(obligation, reviewCtx)) {\n",
    "content generation gate",
)

persist_marker = "async function persistStrictReviewInvocation("
builder = """function buildContentReviewInvocation(
  ctx: PipelineContext,
  reviewerResult: ReviewerSuccessResult & { findings: Record<string, unknown> },
  promptHash: string,
  findingsHash: string,
  attemptId: string,
): ReturnType<typeof buildInvocationEvidence> {
  const { reviewCtx, sessionId, now } = ctx;
  return buildInvocationEvidence({
    obligationId: reviewCtx.obligationId,
    obligationType: 'review',
    mandateDigest: reviewCtx.mandateDigest,
    criteriaVersion: reviewCtx.criteriaVersion,
    parentSessionId: sessionId,
    childSessionId: reviewerResult.sessionId,
    invocationMode: INVOCATION_MODE_SDK_SESSION,
    hostVisible: false,
    promptHash,
    findingsHash,
    invokedAt: reviewerResult.invokedAt ?? now,
    fulfilledAt: reviewerResult.fulfilledAt ?? now,
    attemptId,
    source: EVIDENCE_SOURCE_HOST,
    reviewOutputMode: reviewerResult.reviewOutputMode,
    structuredOutputUsed: reviewerResult.structuredOutputUsed,
    reviewAssuranceLevel: reviewerResult.reviewAssuranceLevel,
    extractionMethod: reviewerResult.extractionMethod,
    modelCapabilityError: reviewerResult.modelCapabilityError,
  });
}

"""
if text.count(persist_marker) != 1:
    raise RuntimeError("content persist marker mismatch")
text = text.replace(persist_marker, builder + persist_marker, 1)
invocation_start = text.find("  const invocation = buildInvocationEvidence({", text.find(persist_marker))
comment_marker = "  // Atomically check evidence reuse AND record invocation in a single\n"
invocation_end = text.find(comment_marker, invocation_start)
if invocation_start < 0 or invocation_end < 0:
    raise RuntimeError("content invocation block not found")
text = (
    text[:invocation_start]
    + "  const invocation = buildContentReviewInvocation(\n"
    + "    ctx,\n"
    + "    reviewerResult,\n"
    + "    promptHash,\n"
    + "    findingsHash,\n"
    + "    attemptId,\n"
    + "  );\n\n"
    + text[invocation_end:]
)
write(path, text)

# 5) Pull standard evidence-result projection out of the strict gate.
path = "src/integration/review/standard-review-pipeline.ts"
text = read(path)
enforce_marker = "async function enforceStandardStrictGate("
standard_result_helper = """function applyStandardEvidenceResult(
  ctx: PipelineContext,
  result: EvidenceRecordResult,
): boolean {
  const { output, reviewCtx } = ctx;
  if (result === 'reused') {
    output.output = strictBlockedOutput('SUBAGENT_EVIDENCE_REUSED', {
      obligationId: reviewCtx.obligationId,
    });
    return true;
  }
  if (result === 'missing') {
    output.output = strictBlockedOutput('REVIEW_MATERIAL_INTEGRITY_FAILED', {
      reason: `no exact review obligation resolved for ${reviewCtx.obligationId}; evidence was not recorded`,
    });
    return true;
  }
  if (result === 'lineage_unavailable') {
    output.output = strictBlockedOutput('REVIEW_ATTEMPT_UNAVAILABLE', {
      obligationId: reviewCtx.obligationId,
      reason: 'SDK review evidence could not bind to the pre-authorized review attempt',
    });
    return true;
  }
  return false;
}

"""
if text.count(enforce_marker) != 1:
    raise RuntimeError("standard strict gate marker mismatch")
text = text.replace(enforce_marker, standard_result_helper + enforce_marker, 1)
old_result_projection = """  if (result === 'reused') {
    output.output = strictBlockedOutput('SUBAGENT_EVIDENCE_REUSED', {
      obligationId: reviewCtx.obligationId,
    });
    return true;
  }
  if (result === 'missing') {
    output.output = strictBlockedOutput('REVIEW_MATERIAL_INTEGRITY_FAILED', {
      reason: `no exact review obligation resolved for ${reviewCtx.obligationId}; evidence was not recorded`,
    });
    return true;
  }
  if (result === 'lineage_unavailable') {
    output.output = strictBlockedOutput('REVIEW_ATTEMPT_UNAVAILABLE', {
      obligationId: reviewCtx.obligationId,
      reason: 'SDK review evidence could not bind to the pre-authorized review attempt',
    });
    return true;
  }

  return false;
"""
text = replace_once(
    text,
    old_result_projection,
    "  return applyStandardEvidenceResult(ctx, result);\n",
    "standard evidence result projection",
)
write(path, text)

# 6) Add direct generation-authority branch coverage. These assertions also lock
# the high-severity forensic invariant against future criteria drift.
write(
    "src/integration/review/assurance-generation.test.ts",
    """import { describe, expect, it } from 'vitest';
import {
  REVIEW_CRITERIA_VERSION,
  REVIEW_MANDATE_DIGEST,
  isCurrentReviewGeneration,
} from './assurance.js';

describe('review generation authority', () => {
  it('accepts exactly the active criteria generation', () => {
    expect(
      isCurrentReviewGeneration({
        criteriaVersion: REVIEW_CRITERIA_VERSION,
        mandateDigest: REVIEW_MANDATE_DIGEST,
      }),
    ).toBe(true);
  });

  it('rejects a stale criteria version', () => {
    expect(
      isCurrentReviewGeneration({
        criteriaVersion: 'p41-v1',
        mandateDigest: REVIEW_MANDATE_DIGEST,
      }),
    ).toBe(false);
  });

  it('rejects a stale mandate digest', () => {
    expect(
      isCurrentReviewGeneration({
        criteriaVersion: REVIEW_CRITERIA_VERSION,
        mandateDigest: 'sha256:stale-generation',
      }),
    ).toBe(false);
  });
});
""",
)
